[FEAT]: 마이프로필의 데이터를 firebase에서 받아옵니다.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #125
Opened 2022-11-15 00:55 UTC by ccdkk

## 🌱 관련 이슈
- Close #112 

## 🌱 구현/변경 사항 및 이유
- firebase에 있는 프로필 데이터와 연결합니다.
- VFUser Model에 파라미터를 추가하였습니다.

## 🌱 PR Point
- firebase의 profile 데이터를 받아오는 부분을 viewWillAppear부분에 넣어 MyPageViewController가 appear 될 때마다 최신 정보가 들어오도록 하였습니다. 그럴 때마다 VFUser에서 profile section을 reload시켜주는데, 이전의 데이터와 같을 때도 reload 시켜주니까 이미지가 없어졌다 생기면서 깜빡 거리는 현상이 있어서, 일단은 기존의 프로필과 같은 경우에는 reload 시키지 않는 방향으로 결정하였습니다. viewWillAppear에서 불러오는 것이 적절한지 궁금합니다
> 깜빡 거리던 현상
![Simulator Screen Recording - iPhone 13 - 2022-11-15 at 09 54 18](https://user-images.githubusercontent.com/91456952/201799781-f1dd1581-428b-46de-afd2-30ae82cc7a0c.gif)
.

## 🌱 참고 사항
![Simulator Screen Recording - iPhone 13 - 2022-11-15 at 09 53 12](https://user-images.githubusercontent.com/91456952/201799672-ded505e8-f045-4f87-b409-768d15c2cdf4.gif)

2022-11-16 01:19 UTC, kelly1422 reviewed
수고하셨습니다~!!

2022-11-16 01:19 UTC, kelly1422 commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +                DispatchQueue.main.async {
p2;
[waek self] 부탁드립니다!

2022-11-16 01:19 UTC, kelly1422 commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        }
이 부분은 사실 로그아웃, 회원탈퇴를 하지 않는 이상 현재 로그인된 사용자는 같을 거라서 이렇게 뷰가 나타날때마다 유저정보를 가져오는게 좀 비효율적이라는 생각이 들긴 하네욤.. 나중에 유저 디폴트에 로그인이나 회원가입하면 현재 유저 정보를 한번 저장해놓고 계속 가져다 쓰다가 로그아웃이나 회원탈퇴를 할때 유저디폴트에서 값을 삭제시켜주고 하면 더 효율적이지 않을까 싶습니다. 나중에 좀 정리되면 이야기 나눠보는게 좋을거 같아요!

2022-11-16 01:19 UTC, kelly1422 commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        case TableSection.setting.rawValue: return tableCellList.count
가독성이 더 좋아졌군요!!

2022-11-16 01:19 UTC, kelly1422 commented on Vegeting/Global/Models/VFUser.swift
> +    let ageGroup: String
p2;
이건 나이대를 저장하는 프로퍼티인것 같은데, 저희가 가입할때는 출생년도를 받고 있어서요, 해당 프로퍼티를 Int타입인 birth? 와 같은걸로 바꾸고 Int를 익스텐션해서 나이대로 변환해주는 메소드 하나 작성해서 프로필관련 테이블 셀을 configure할 때는 birth.ageGroup() 과 같은 방식으로 해야하지 않을까요??

2022-11-16 02:25 UTC, yudonlee requested changes
데이크 비록 짧은 코드였지만, 쓸게 아주 많은 부분이였던거 같습니다! 코멘트 참고하셔서 수정해주시면 좋을 것 같습니다~

2022-11-16 02:25 UTC, yudonlee commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        }
p2;
Task 내부에서도 weak self를 필수적으로 작성하셔야 합니다. 
escaping closure가 아니고, crash가 throw되지 않아 중간에 클로저가 중단되진 않습니다.
하지만 강한참조로 인해서 viewcontroller의 deinitialization이 지연되는 걸 확인할수 있습니다. 
관련 동영상 참고 바랍니다! 
# 강한참조
https://user-images.githubusercontent.com/39371835/202065361-c2dd899e-0046-49ba-8e35-72443e8ae889.mov

# 약한참조

https://user-images.githubusercontent.com/39371835/202065481-0ddc855a-f6a4-4fe0-91a4-ae6eb2af70bc.mov

2022-11-16 02:25 UTC, yudonlee commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        case TableSection.setting.rawValue: return tableCellList.count
p2;
switch case후 statement는 줄바꿈을 해주세요.

2022-11-16 02:25 UTC, yudonlee commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        case TableSection.profile.rawValue:
section을 사용해서 가독성을 높인점이 좋은것 같습니다~!

2022-11-16 02:25 UTC, yudonlee commented on Vegeting/Global/Models/VFUser.swift
> +    let ageGroup: String
저도 제로 생각과 동일합니다~

2022-11-16 02:25 UTC, yudonlee commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +                    self.tableView.reloadSections(.init(integer: TableSection.profile.rawValue), with: .none)
reloadSection은 처음봤는데, 특정 section만 reload해주는 고마운 친구군요! 아주 좋습니다

2022-11-16 02:25 UTC, yudonlee commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        }
아무래도 프로필 사진이나 닉네임이 변경됐을경우를 대비해서 구현하신 것 같네요. 
개인적으로는 NotificationCenter등으로 로컬에서 서버로 request했다는 걸 알려주면, 그때 user를 reload 받아온다면 더 좋을거 같습니다.

2022-11-16 10:21 UTC, ccdkk commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +                DispatchQueue.main.async {
헉 이걸 놓쳤군요! 반영하겠습니다

2022-11-16 10:24 UTC, ccdkk commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        }
아무래도 닐이 말씀해주신 것처럼 프로필이 변경되얶을 경우에 대비하여 viewWillApeear에서 불러오되 이전 데이터와 같다면 리로드 하지 않는 것으로 구현해놨는데 필요없는 부하가 있을 것 같네요. 닐이 말씀해주신 대로 프로필이 수정이 된다면 신호를 줘서 불러오는 방식으로 하면 좋을 것 같습니다. 해당 기능은 프로필 수정 기능이 구현된 다음에 작업하는게 좋을 것 같다는 생각이 드는데 백로그에 남겨놓고 나중에 진행해도 괜찮을까요?

2022-11-16 10:26 UTC, ccdkk commented on Vegeting/Global/Models/VFUser.swift
> +    let ageGroup: String
오 좋은 방법이네요!! 반영하도록 하겠습니당

2022-11-16 14:04 UTC, ccdkk commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        }
와 이렇게 보니까 확 차이가 느껴지네요. 강한 참조가 되는 경우에는 뷰컨이 dismiss되어도 Task가 진행되어서 deinit이 지연되는 건가요?

2022-11-16 14:07 UTC, ccdkk commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        case TableSection.setting.rawValue: return tableCellList.count
return 값이 단순할 경우 굳이 줄바꿈하지 않아도 가독성이 떨어지는 느낌이 안드는 것 같은데,
혹시 줄바꿈을 해줘야하는 이유가 있을까요?

2022-11-16 15:15 UTC, ccdkk commented on Vegeting/Global/Models/VFUser.swift
> +    let ageGroup: String
ageGroup을 birth로 바꾸면서 firebase 데이터도 수정했습니다~!

2022-11-17 08:39 UTC, kelly1422 commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        }
백로그에 남겨주시지요!

2022-11-18 02:15 UTC, wonhui-kim reviewed
코드가 완전 깔끔하네요! ✨

2022-11-18 02:15 UTC, wonhui-kim commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        case TableSection.setting.rawValue: return tableCellList.count
사실 이것도 저희가 컨벤션을 설정하면 될 문제라고 생각합니다!

다만 저는 switch-case문을 저렇게 한 줄로 쓰는 경우가 어색하게 느껴지네요.
개인적으로 enum의 case 에서 rawValue를 주는 것과 유사하게 느껴져서 
한 줄로 쓰면 각 case의 처리문이 아니라 case를 정의해주는 것 같아보여요~

여태까지 case에서 단순 break로 처리해주어도 개행을 해주는 형태가 익숙해서
저희가 한 번 얘기해보면 좋을 듯 해요~

2022-11-18 02:15 UTC, wonhui-kim commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        case TableSection.profile.rawValue:
각 섹션의 역할이 잘 보여서 너무 좋아요! 👍

2022-11-18 02:15 UTC, wonhui-kim commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
p4;

개행 삭제해주세요 🙂

2022-11-18 12:06 UTC, ccdkk commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        case TableSection.setting.rawValue: return tableCellList.count
좋아요 한 번 얘기해 봅시다!

2022-11-18 12:07 UTC, ccdkk commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
[7961408](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/125/commits/79614083937f47fd7bb96e10a1332b183a65cc19)반영했습니다!

2022-11-20 05:40 UTC, wonhui-kim approved these changes
수고하셨습니다~~ 😄

2022-11-20 06:02 UTC, yudonlee requested changes

2022-11-20 06:02 UTC, yudonlee commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
>          default: return 0
p3;
case 후 실행 statement 줄바꿈이라면 통일하는게 더 좋을거 같아요!

2022-11-20 07:54 UTC, ccdkk commented on Vegeting/Global/Extensions/Int+Extension.swift
> +    func toAgeGroup() -> String{
[94b1716](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/125/commits/94b1716d59ed5e46db3b9065ea041496ece5da7c)반영했습니다!

2022-11-20 07:54 UTC, ccdkk commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
>          default: return 0
[94b1716](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/125/commits/94b1716d59ed5e46db3b9065ea041496ece5da7c)반영했습니다!

2022-11-21 01:51 UTC, kelly1422 approved these changes
수고하셨습니다~

2022-11-21 01:56 UTC, yudonlee commented on Vegeting/Screens/MyPage/ViewController/MyPageViewController.swift
> +        }
> 와 이렇게 보니까 확 차이가 느껴지네요. 강한 참조가 되는 경우에는 뷰컨이 dismiss되어도 Task가 진행되어서 deinit이 지연되는 건가요?

네 그렇습니다. delayed deinitialization이락 medium에선 얘기하더라고요. 테스트해봤는데 생각보다 꽤 커서 놀랐습니다.

2022-11-21 01:57 UTC, yudonlee approved these changes
고생하셨습니다.!

2022-11-21 01:58 UTC, merged