[FEAT]: UserProfileView 보충(추가) 사항을 구현합니다.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #133
Opened 2022-11-15 14:26 UTC by wonhui-kim

## 🌱 관련 이슈
- #132 

## 🌱 구현/변경 사항 및 이유

- nicknameTextField 하단에 현재 입력한 글자수가 뜨도록 했습니다.ㅋ
- nicknameTextField를 지우는 경우를 대비해 buttonInactive() 함수를 추가하였습니다.
- nextButton을 global bottomButton을 상속받는 것으로 교체했습니다.
- SE 기종 호환을 위해 autoLayout의 constant를 비율로 조정했습니다.
- profileImageView 클릭 시 PHPickerView가 뜨도록 했습니다.
- UIView를 상속받는 UIImageView 클릭 이벤트는 addGestureRecognizer를 사용하여 구현하였습니다.

## 🌱 PR Point
###  addGestureRecognizer 메서드가 실행되지 않는 문제 해결
해당 문제는 profileImageView 프로퍼티를 let으로 선언했기 때문이었습니다.

<img width="777" src="https://user-images.githubusercontent.com/96123303/201938794-f3ec92d0-2ba7-4eea-afd7-eca2fd64c13a.png">

위와 같이 UIView 탭(터치) 이벤트 처리를 위해 addGestureRecognizer 메서드를 사용하였고, 
메서드의 파라미터로 UITapGestureRecognizer를 통해 target을 self로, action을 PHPicker를 띄우는 함수 호출로 구현했습니다.

여기서 target인 self로 인해 프로퍼티를 let으로 선언했을 경우 메서드 호출이 일어나지 않았습니다.
 - 위의 설명을 더 보충하자면 let으로 profileImageView를 구현하면 ViewController가 self임을 인지하기도 전에(ViewController가 생성되기도 전에) 해당 메서드가 실행되기 때문에 addGestureRecognizer가 제대로 실행되지 않게 됩니다. 
 - lazy var는 인스턴스에 의존적이므로 ViewController가 self임을 인지한 후에 해당 프로퍼티에 호출되는 순간에 생성되기 때문에 addGestureRecognizer가 제대로 실행됩니다.
 - 따라서 **해당 문제를 let -> lazy var로 변경함으로써 해결**했습니다.
- 위의 설명은 button의 addTarget 또한 동일하게 적용됩니다.

## 🌱 참고 사항

**구현 화면**
<img src="https://user-images.githubusercontent.com/96123303/201911545-ae891fe8-2f5e-4060-b4d8-9d769cff74ab.mp4" width=400/>

2022-11-15 14:52 UTC, ccdkk reviewed
고생하셨습니다! 꼼꼼한 PR 감사해요~

2022-11-15 14:52 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +    private lazy var profileImageView: UIImageView = {
굳이네용
이전에 button에 addtarget을 적용할 때도 lazy var로 선언해 주지 않으면 target 자리에 self를 넣지 못하더라구요
대신에 해당 viewController.self 로 넣어줬던 것 같습니다. 그게 프로퍼티가 viewController를 인식하기 전에 생성되기 때문이군요!
덕분에 배워갑니다~!

2022-11-15 14:52 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +    private func presentPHPicker() {
UIView에서도 사용해야 하다보니 함수 네이밍이 버튼컨벤션에서 브로드해진 형태로 되었군요
저는 좋은 것 같습니다!!

2022-11-15 14:52 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +        label.textColor = UIColor(hex: "#8E8E93")
p2;
이 부분 hi-fi color pr이 머지되고 나면 extension에 있는 color로 변경 부탁드려요!

2022-11-16 02:36 UTC, yudonlee requested changes
고생하셨습니다. lazy var를 직접 원인을 찾아내서 몸소 실감하신 점이 너무 좋네요🥹

2022-11-16 02:36 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +    private lazy var profileImageView: UIImageView = {
저는 이걸 Xcode가 warning해줘서 운좋게 이런 트러블 슈팅 없이 lazy로 바꿨는데, 경고없이 찾아내는게 쉽지 않았을거 같습니다. 수고하셨어요.

2022-11-16 02:36 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +        let button = BottomButton()
디자인 시스템의 위대함을 보고 있네요. 추후에 Bottom Button에 initializer를 추가해서 title를 받도록 해야겠습니다.

2022-11-16 02:36 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +
p3; 개인적인 의견이지만, text를 넘겨주면 button의 enable disable을 판단해서 버튼의 상태까지 바꿔줄수 있는 함수로 바꿔주시면 더 좋을것 같아요!

2022-11-16 02:36 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +    private func presentPHPicker() {
p3;
버튼 tapped네이밍 컨벤션은 지키고 해당 objc 함수 내에서 presentPHPicker로 하는게 더 가독성이 좋을것 같아요!
```swift
@objc
func imageViewTapped() {
   presentPHPicker()
}
@objc
func buttonTapped() {
   presentPHPicker()
}
```
나중에 테스트등 별도의 활동을 하기가 더 편할거 같습니다!

2022-11-17 04:06 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +    private func presentPHPicker() {
그렇네요! 함수를 분리해주면 더 좋을 것 같아요~
[반영](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/133/files#diff-d95417c458a8528974d98adab570fc3e6ffedf546ea53c010fbdf052c46d30d8R161-R172)했습니다 😄

2022-11-17 04:06 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +        label.textColor = UIColor(hex: "#8E8E93")
[반영](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/133/files#diff-d95417c458a8528974d98adab570fc3e6ffedf546ea53c010fbdf052c46d30d8R66-R67)했습니다~

2022-11-17 04:07 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +
너무 좋아요!
저도 하나의 함수에 너무 많은 내용이 들어가있는게 아닌가 하고 고민했는데 덕분에 [수정](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/133/files#diff-d95417c458a8528974d98adab570fc3e6ffedf546ea53c010fbdf052c46d30d8R200-R210)했습니다 😁

2022-11-17 04:24 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
>              let index = text.index(text.startIndex, offsetBy: nicknameMaxLength)
```suggestion
        //maxLength 이상의 글자를 붙여넣을 경우 잘라주는 역할
        if textLength > nicknameMaxLength {
            let index = text.index(text.startIndex, offsetBy: nicknameMaxLength)
```
기존에 선언된 변수를 활용하면 더 좋을 거 같습니다~

2022-11-17 04:27 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
>              let index = text.index(text.startIndex, offsetBy: nicknameMaxLength)
[수정](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/133/files#diff-d95417c458a8528974d98adab570fc3e6ffedf546ea53c010fbdf052c46d30d8R188-R190)하였습니다~

2022-11-17 06:39 UTC, yudonlee approved these changes
수고 많으셨어요!!!~~ 😁

2022-11-17 09:57 UTC, ccdkk approved these changes
어프루브입니다. 고생하셨습니다!

2022-11-17 09:58 UTC, merged