[FEAT]: 파이어베이스에 이미지 파일을 업로드하고 다운로드 하는 api를 작성합니다.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #139
Opened 2022-11-17 10:32 UTC by kelly1422

## 🌱 관련 이슈
- close #122 

## 🌱 구현/변경 사항 및 이유

### 1. FirebaseStorage 패키지를 추가
이미지 파일을 파베에 저장하기 위헤 FirebaseStorage 패키지를 추가했습니다
### 2. 사진 업로드 uploadImage() 함수 작성
이미지와 같은 파일은 다른 문서데이터와 다르게 FirebaseStore가 아닌 FirebaseStorage에 저장해야 합니다.
그런 다음 FirebaseStorage에 저장된 사진의 url을 받아서 문서로 저장합니다.
해당 함수는 FirebaseStorage에 매개변수로 받은 UIImage를 저장하고, 저장된 사진의 url을 쓸 escaping 클로저를 반환하는 함수입니다.
FirebaseStorage에 사진이 저장될 경로를 정해줄 수 있는데, 일단 해당 함수를 호출할때 원하는 경로를  매개변수로 입력받도록 하였습니다.
### 3. 사진 다운로드 downloadImage() 함수 작성
사진의 url을 입력하면 그 사진을 불러와주는 함수입니다.

### 4. 사진의 해상도, 화질 조절을 통한 파일 크기 조정
사진의 해상도가 너무 높으면, 저장할 파일의 크기가 그만큼 커져 저장하고 다운로드 하는 속도가 느려질 수 있습니다.
이를 조절할 수 있는 UIImage+Extension 를 만들었습니다.
scaledToSafeUploadSize 프로퍼티는 이미지의 더 긴부분의 길이가 480을 넘으면 더 긴부분의 길이를 480에 맞게 크기 조정한 이미지를 가집니다.

## 🌱 PR Point
잘 이해가 가는 코드인지, uploadImage()와 downloadImage() 어떻게 써야할지 감이 오는지!?
뒤에 올릴 pr에서 uploadImage를 사용했으니 이해가 안간다면 같이 보셔도 좋을것 같습니다!

2022-11-18 01:54 UTC, wonhui-kim requested changes
수고하셨습니다 😁
File Changed를 보니 파일이 UIImage+Extension, UIImage_Extension 2개가 올라와있는데,
브랜치에서는 UIImage+Extension 확인이 안 되는걸 보니 파일을 삭제하고 새로 만드신 것 같아보여요!

파일 하나(UIImage+Extension.swift)는 reference로 삭제하셔서 제로 로컬에 남아있는 것 같아요!
같이 올라와버렸네요 🥲

수정해주세요~~

2022-11-18 01:54 UTC, wonhui-kim commented on Vegeting.xcodeproj/project.pbxproj
> +				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
Signing에서 Automatically manage signing 체크를 안하시고 커밋하신 것 같아요~
수정 부탁드려요 🙂

2022-11-19 11:25 UTC, ccdkk reviewed
고생하셨습니다!! 얼른 머지되면 빨리 가져다 써야겠군요! 좋은 코드 감사합니다.

2022-11-19 11:25 UTC, ccdkk commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +    }
q;
putData의 escaping Closure가 `(StorageMetadata?, Error?) -> Void)?`요런 형태인데 Error 처리를 안해주어도 되나요? 
같은 맥락에서 downloadURL의 escaping Closure는 `(URL?, Error?) -> Void` 요런 형태이므로 URL을 guard 나 if let 으로 풀어주고 error 처리를 해주면 어떨까 합니다. 아래는 fireBase document에서 가져온 sample인데 요렇게 에러처리를 하고 있어서요!
```Swift
// Data in memory
let data = Data()

// Create a reference to the file you want to upload
let riversRef = storageRef.child("images/rivers.jpg")

// Upload the file to the path "images/rivers.jpg"
let uploadTask = riversRef.putData(data, metadata: nil) { (metadata, error) in
  guard let metadata = metadata else {
    // Uh-oh, an error occurred!
    return
  }
  // Metadata contains file metadata such as size, content-type.
  let size = metadata.size
  // You can also access to download URL after upload.
  riversRef.downloadURL { (url, error) in
    guard let downloadURL = url else {
      // Uh-oh, an error occurred!
      return
    }
  }
}
    
```

Ref: https://firebase.google.com/docs/storage/ios/upload-files

2022-11-19 11:25 UTC, ccdkk commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +        }
p2;
completion(nil)로 nil값을 넘기는 것보다 completion 호출 없이 error 처리를 하면 nil값이 들어간 completion이 들어가는 코스트 없이 진행할 수 있지 않을까요? 물론 클로져에서 guard를 해주겠지만.. 미연에 방지하는..? firebase document 샘플 코드를 첨부합니다. 요긴 요렇게 했군요.
```Swift
// Create a reference to the file you want to download
let islandRef = storageRef.child("images/island.jpg")

// Download in memory with a maximum allowed size of 1MB (1 * 1024 * 1024 bytes)
islandRef.getData(maxSize: 1 * 1024 * 1024) { data, error in
  if let error = error {
    // Uh-oh, an error occurred!
  } else {
    // Data for "images/island.jpg" is returned
    let image = UIImage(data: data!)
  }
}
```
Ref: https://firebase.google.com/docs/storage/ios/download-files

2022-11-20 14:05 UTC, kelly1422 commented on Vegeting/Global/Extensions/UIImage+Extension.swift
> +        }
넵 graphic context를 생성하고 사용한 뒤 삭제하는 함수입니다. 마지막에 호출이 되어야 하는데, 
```swift
 private func image(scaledTo size: CGSize) -> UIImage? {
        defer {
            UIGraphicsEndImageContext()
        }
        
        UIGraphicsBeginImageContextWithOptions(size, true, 0)
        draw(in: CGRect(origin: .zero, size: size))
        
        return UIGraphicsGetImageFromCurrentImageContext()
    }
```
코드를 보면 마지막에 현재 graphic context에 그림을 그려주고 그것을 반환해주고 있는데요, 이렇게 return을 하고 난 뒤에 UIGraphicsEndImageContext()를 해주면 실행되지 않기 때문에 defer을 사용했습니다.

```swift
 private func image(scaledTo size: CGSize) -> UIImage? {
        UIGraphicsBeginImageContextWithOptions(size, true, 0)
        draw(in: CGRect(origin: .zero, size: size))
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return image
    }
```
이런식으로 작성하면 defer을 사용하지 않아도 됩니다!
근데 이제 저런식으로 코드 실행 뒤 마지막에 꼭 실행시켜줘야 하는 함수는 저렇게 쓰는게 좋은것 같아서 저렇게 작성해보았습니다

2022-11-20 14:10 UTC, kelly1422 commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +        let imageName = UUID().uuidString + String(Date().timeIntervalSince1970)
사실 생성한 uid가 겹칠 확률은 정말 희박하지만 그래도 아예 불가능한것은 아니니, 추가로 Date까지 넣었습니답

2022-11-20 15:56 UTC, kelly1422 commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +              let data = scaledImage.jpegData(compressionQuality: 0.4) else { return completion(nil)}
[2686d24](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/139/commits/2686d244585f04d0e1fe4dd272449d8b3fa12cc7)
반영완료!

2022-11-20 15:58 UTC, kelly1422 commented on Vegeting.xcodeproj/project.pbxproj
> +				"CODE_SIGN_IDENTITY[sdk=iphoneos*]" = "iPhone Developer";
[eda1fd5](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/139/commits/eda1fd589ddd66a830443d478c02b811be3d72a5)
[4e1a747](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/139/commits/4e1a74765942ace35ab52815d185d21a762766b1)
반영완료 했습니다! 이미지 익스텐션 파일이 저리 꼬여있을줄 상상도 못했는데.. 감사합니당

2022-11-20 16:09 UTC, ccdkk commented on Vegeting/Global/Extensions/UIImage+Extension.swift
> +        }
오호 return이 된 이후에 실행이되는군요? 신기합니다. 좋은 키워드 알아가요~~!

2022-11-20 16:09 UTC, ccdkk commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +        let imageName = UUID().uuidString + String(Date().timeIntervalSince1970)
꼼꼼하시네요 굳

2022-11-23 01:28 UTC, kelly1422 commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +    }
넵 저도 다시 찾아봤는데, 에러 처리를 보통 해주고 있더군요!
일단 저희는 사진을 업로드 한뒤에, 사진이 저장된 url을 FireStore에 다시 저장해주어야 하기 때문에

```swift
imageReference.putData(data, metadata: metaData) { _, _ in
            imageReference.downloadURL { url, _ in
                completion(url)
            }
        }
```
putData (사진을 Storage에 저장 ), downloadURL(사진을 저장한 후 저장된 url을 ) 두가지 메소드를 사용하고 있습니다.
일단 첫번재 메소드 컴플리션 핸들러 내부에서 downloadURL을 사용하므로 downloadURL에서 에러처리를 해주면 되겠다 생각해, downloadURL 컴플리션 핸들러에

```swift
imageReference.putData(data, metadata: metaData) { _, _ in
            imageReference.downloadURL { url, _ in
                guard let url = url else { return completion(nil) }
                completion(url)
            }
        }
```

위와 같이 가드문을 작성해주었습니다.

(다시 보니, 위는 putData의  metadata에 nil 값을 넘겨주고 있더라구요, 저는 파일이 이미지파일이라고 지정해주기 위해 metaData의contentType을 "image/jpeg"로 지정해 넘겨주고 있어 metaData에 nil 값을 리턴받을 상황이 없다 판단했습니다!
https://firebase.google.com/docs/storage/ios/file-metadata)

2022-11-23 01:35 UTC, kelly1422 commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +        }
위와 같은 방식으로 작성을 하여도 컴플리션 핸들러는 모든 상황에 실행되어야하기 때문에 
```swift
reference.getData(maxSize: megaByte) { data, error in
  if let error = error {
    completion(nil)
  } else {
    completion(UIImage(data: data!))
  }
}
```
위와 같이 작성되어야 합니다!
하지만 위와 같이 작성할 경우 else (에러가 발생하지 않은 경우), 다운로드 받은 데이터가 옵셔널이기에 강제언래핑을 해주고 있는데,
다운로드 받은 데이터를 gaurd문으로 작성해주면 옵셔널 값이 아닐 뿐더러 에러처리도 함께 해줄 수 있어 좋은것 같습니다

2022-11-23 10:08 UTC, ccdkk commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +    }
고생하셨씁니다!!

2022-11-23 10:10 UTC, ccdkk commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +        }
아하 컴플리션 핸들러 부분이 옵셔널이 아니기 때문에 꼭 넣어줘야하는군요! 고생하셨습니다!

2022-11-23 10:10 UTC, ccdkk approved these changes
굳굳입니다 !

2022-11-24 02:54 UTC, wonhui-kim approved these changes
수고하셨습니다~!

2022-11-24 02:54 UTC, merged