[FEAT]: 모임글 생성시 선택한 사진도 파베에 저장하기.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #141
Opened 2022-11-17 11:21 UTC by kelly1422

## 🌱 관련 이슈
- close #131

## 🌱 구현/변경 사항 및 이유
### 1. 사진 선택하기를 누르면 액션시트
액션시트를 통해 
`기본이미지 선택`, `앨범에서 선택`, `취소`
를 할 수 있도록 하였습니다.
기본이미지를 선택하면 모임 커버 이미지가 기본이미지로 바뀝니다. (이미지는 추후에 넣을 예정, 임시로 아무 이미지 넣어놨습니다.)
앨범에서 선택을 하면 PHPickerViewController 띄워 사진을 선택할 수 있습니다.
### 2. 모임글 작성시 선택한 커버이미지를 저장
1. 현재 선택된 커버이미지를 가져옵니다.  기본이미지: nil, 앨범에서 선택한 사진: UIImage
2. isDefaultImage 가 false, 즉 앨범에서 선택한 사진의 경우에만 앞에서 작성한 FirebaseStorageManager.uploadImage() 를 통해 파베에 이미지 파일을 저장해줍니다.
-> 기본이미지인 경우 최종적으로 파베에 저장될 club의 coverImageURL 가 nil 값이고,
      앨범에서 선택한 사진의 경우  coverImageURL에는 uploadImage()를 통해 파베에 저장된 사진의 url 값이 들어갑니다.
### 3. 만나는 장소 저장
club 구조체에 만나는 장소를 나타낼 프로퍼티가 없어 추가해주고, 추가로 파베에 저장되도록 하였습니다.
### 4. 메인뷰와 작성 플로우 연결
모임글을 보여주는 메인뷰에서 쓰기 버튼을 누르면 모임 작성화면으로 연결되도록 하였습니다.
탭바를 숨기도록 하였고, 마지막 작성을 완료하고 등록 버튼을 누르면 메인뷰로 popToRootViewController 되도록 했습니다.

### 4. 재사용을 더 잘 할 수 있도록 PhotoPickerView를 수정
원래는 PhotoPickerView를 사용하는 SecondCreateGroupViewController에서 PhotoPickerView의 UI적인 요소만 쓸 수 있었는데,  PhotoPickerView 내에 PHPickerViewControllerDelegate를 체택하여 PHPickerViewController 띄우는 코드를 작성,
`기본이미지 선택`, `앨범에서 선택`, `취소` 액션시트 띄우는 코드 또한 PhotoPickerView 내에서 작성하였습니다.
하지만 사실상 액션시트와 포토픽커는 PhotoPickerView를 사용하는 뷰컨트롤러에서 띄워줘야하기 때문에 PhotoPickerViewDelegate를 작성해 해당 액션시트와 PHPickerViewController를 뷰컨으로 넘겨주도록 했습니다.

## 🌱 PR Point
하하 설명이란게 참 어렵군요.. 말이 잘 이해가 가시는지요.. 이해 안가는 부분이 있다면 물어봐주세요!

## 🌱 참고 사항
![Simulator Screen Recording - iPhone 13 - 2022-11-17 at 20 19 01](https://user-images.githubusercontent.com/80809782/202432897-3b26f1b4-57bf-4cd7-9b98-3e732610f506.gif)<img width="400" alt="스크린샷 2022-11-17 오후 7 39 41" src="https://user-images.githubusercontent.com/80809782/202424902-b73558c6-6123-44de-bd19-2655b57d4d95.png">

<img width="800" alt="스크린샷 2022-11-17 오후 7 38 37" src="https://user-images.githubusercontent.com/80809782/202424651-f6a2abe5-058a-493f-9cf3-b27dd0aca8d5.png">

2022-11-21 14:08 UTC, yudonlee commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +}
p3;
기존에 FirebaseManager와 AuthManager가 singleton으로 구현된 상황인데, 두가지 방식에서 static function과의 성능 차이의 article은 발견하지 못한것 같습니다. 아무래도, 기존에 구현된 함수들이 singleton으로 사용되고 있는 상황이기 때문에 통일하는게 어떨까 조심스럽게 건의드려봅니다!

2022-11-21 14:25 UTC, yudonlee commented on Vegeting.xcodeproj/project.pbxproj
> +		};
q;
Framework는 어떤 역할을 하는 폴더일까요? 빈폴더라 궁금합니다~!

2022-11-21 14:28 UTC, yudonlee commented on Vegeting/Global/Extensions/UIImage+Extension.swift
> +    }
p2;
extension의 경우 되도록 직접 구현한것들이 아니라면 지양하고, 이전에 것들을 deprecated할 의향이 있습니다. 어떠한 이유로 해당 extension을 썼으며 아래 함수들은 어떤 방식으로 작동하는지 여쭤보고 싶어요! autolayout과 maskToBounds로 해결될 수 있다고 생각합니다.

2022-11-21 14:33 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/Component/PhotoPickerView.swift
> +    var isDefaultImage = true
p1;
class내 변수들은 private으로 관리해주세요! 필요하다면 함수등으로 빼도록 해야할 것 같습니다.~~

2022-11-21 14:37 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/Component/PhotoPickerView.swift
> +        }
p1;
기본 이미지로 변경되었을 떄, textLabel을 ""하는 처리 구현이 안되어 있는 것 같아요!

2022-11-22 00:09 UTC, yudonlee requested changes

2022-11-22 00:09 UTC, yudonlee commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +        guard let scaledImage = image.scaledToSafeUploadSize,
p3;
escaping handler는 결국, 비동기 처리를 위해서 사용되는건데 에러를 리턴할때 다소 어려운 점이 있었어요.
그를 보완하기 위해 Result문법을 도입했습니다!
https://developer.apple.com/documentation/swift/result
해당 타입은, 성공과 에러를 처리하기에 가독성 좋고, 이해하기 쉬운 형태로 제공됩니다.
FirebaseManager에 제가 사용한 escaping handler 방식을 보시면 더욱 좋을것 같습니다.
```suggestion
    static func uploadImage(image: UIImage, folderName: String, completion: @escaping (Result<URL, Error>) -> Void) {
        guard let scaledImage = image.scaledToSafeUploadSize,
```

2022-11-23 03:52 UTC, kelly1422 commented on Vegeting/Global/Models/VFUser.swift
> +    let profileImageURL: URL?
현재 잘 저장되고, 잘 불러와져서 URL 타입의 경우는 자동으로 파베에 저장할때는 String 타입으로 타입캐스팅이 일어난 뒤 인코딩 되고, 저장이되고 불러올때도 디코딩 후 url 타입으로 타입캐스팅 해주는것 같습니다!

2022-11-23 04:01 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
>          textField.layer.backgroundColor = UIColor.systemGray4.cgColor
[a701c02](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/a701c02f6b84586ad50525418a1f8d1c84298259)
적용완료!

2022-11-23 04:01 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
>          var pickerView = PhotoPickerView()
[a701c02](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/a701c02f6b84586ad50525418a1f8d1c84298259)
적용완료!

2022-11-23 04:01 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
>                          coverImageURL: nil)
[8cd4c11](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/8cd4c11137e522712bab62cc1c5d30d4c35847b7)
적용완료!

2022-11-23 04:02 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +                guard let vfUser = await firebaseManager.requestUser() else { return }
[6a03c2b](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/6a03c2b9949b9ee1c12031d870a54c37337e1825)
적용완료ㅂ!

2022-11-23 04:02 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
>          let firebaseManager = FirebaseManager.shared
[6a03c2b](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/6a03c2b9949b9ee1c12031d870a54c37337e1825)
적용완료ㅂ!

2022-11-23 04:04 UTC, kelly1422 commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +}
[5f678e0](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/5f678e0e51bc791b31d5ecd6a64323c475677a85)
적용완료!

2022-11-23 04:05 UTC, kelly1422 commented on Vegeting.xcodeproj/project.pbxproj
> +		};
헉 이런걸 만들었었나.. 잘못만든것 같습니다
[002c6b2](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/002c6b241898f0f6a57a53eeae706feae9b730a1)
삭제 완료!

2022-11-23 04:45 UTC, kelly1422 commented on Vegeting/Global/Extensions/UIImage+Extension.swift
> +    }
넵, 이건 UI에 보여질 이미지 사이즈를 조절하는게 아니라, 파베에 저장될 이미지의 크기를 조절하는 것입니다. 
이미지 크기가 너무 크면 저장되는 파일의 크기가 너무 커져, 데이터를 저장하고 읽어들이는 시간이 더 오래걸리게 되는 것을 방지하기 위해 추가한 코드입니다. 
해상도에 대해서 아주 잘 알지는 못하지만 보통 480p, 720p, 1080p, 이런식으로 해상도를 조절하는데, 
위의 코드는 더 긴 이미지 사이즈를 최대 480으로 해주어 480p 해상도보다 높지 않게 이미지 자체의 사이즈를 줄여줍니다.

<img width="200" alt="스크린샷 2022-11-23 오후 1 37 02" src="https://user-images.githubusercontent.com/80809782/203470759-132d1482-90c3-41dc-8393-a6d767a76223.png"><img width="200" alt="스크린샷 2022-11-23 오후 1 38 36" src="https://user-images.githubusercontent.com/80809782/203470731-904ecfb7-8a70-46e4-9a70-0268b396d549.png">

각각 해당 익스텐션을 사용하지 않은것과 사용한 것으로 저장되는 이미지 사이즈가 4배정도 차이나는것을 확인할 수 있습니다.

2022-11-23 04:45 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/Component/PhotoPickerView.swift
> +    var isDefaultImage = true
[ab56c05](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/ab56c05997a2c1580ef15fc27c6edcb2bf438a66)
적용완료!

2022-11-23 04:46 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/Component/PhotoPickerView.swift
> +        }
이건 하이파이 적용할때 따로 하려고 했어서요! 어차피 다 바뀔거 같아서 일단 냅뒀습니당
지금 데이크가 하고 계셔서 데이크에게 말해놓을게요!

2022-11-23 11:45 UTC, kelly1422 commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +        guard let scaledImage = image.scaledToSafeUploadSize,
[f7cab87](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/f7cab8772309edb8520e28fd9ac3c7428c0659ac)
적용해보았습니다! 보시고 피드백 부탁드려요!, download 함수는 다운로드 함수 부분에서 수정하겠습니다!

2022-11-24 08:44 UTC, yudonlee commented on Vegeting.xcodeproj/project.pbxproj
> +		};
아이쿠! 해당 폴더는 "A framework is a hierarchical directory that encapsulates shared resources, such as a dynamic shared library, nib files, image files, localized strings, header files, and reference documentation in a single package. " 관장하는 중요한 폴더네요.. 큰일날뻔 했습니다 죄송해여~ !

2022-11-24 08:50 UTC, yudonlee commented on Vegeting/Global/Extensions/UIImage+Extension.swift
> +    }
안녕하세요 제로, apple first party에서 사진의 압축을 지원하는 기능들이 있습니다. 
https://developer.apple.com/documentation/uikit/uiimage/1624115-jpegdata을 참고하길 바래요! 
제가 개인적으로 여쭤봤던 것은 동작원리가 불분명한 코드를 지향하고자 동작원리를 알고 싶어서 여쭤본거였어요~!

2022-11-24 09:38 UTC, yudonlee requested changes

2022-11-24 09:38 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/Component/PhotoPickerView.swift
> +    }
p2;
swift에서 get naming은 지양해주세요! isImageSelectionDefault는 어떨까요?
출처 
https://github.com/StyleShare/swift-style-guide

2022-11-24 09:38 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/Component/PhotoPickerView.swift
> +    var isDefaultImage = true
getNaming등으로 request Change 요청드립니다~~!

2022-11-24 09:44 UTC, yudonlee requested changes

2022-11-24 09:44 UTC, yudonlee commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +
p1;
guard let으로인해 return에 completion handler를 한 라인에 넣어두신것 같습니다.
하지만 의미는 서로 상충되니
```swift
else {
    completion(.failure(StorageError.uploadFail))
    return
}
```
와같이 closure 처리와 리턴이 분리되는게 좋을거 같아요!

2022-11-24 09:44 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
>          if !coverPickerView.getIsDefaultImage() {
p1;
swift에서는 get사용을 지양해주세요~
저흰 server로부터 데이터를 불러올때 request를 사용하기로 했었습니다~!

2022-11-24 09:44 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
>              guard let image = coverPickerView.getImageView() else { return completion(nil) }
p2;
위와 마찬가지로, 클로저 처리문과 return문은 분리해주세요~!

2022-11-24 11:21 UTC, kelly1422 commented on Vegeting.xcodeproj/project.pbxproj
> +		};
흠... 근데 현재 디벨롭 브랜치에는 없는 폴더인거 같고, 없어도 잘 돌아가는거 같고, 말그대로 빈 폴더였어서요, 굳이 다시 돌려 놔야할까요?

2022-11-25 02:59 UTC, yudonlee commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +
p1;
singleton 일경우 private init을 붙여주세요.

2022-11-25 03:44 UTC, kelly1422 commented on Vegeting/Global/Extensions/UIImage+Extension.swift
> +    }
https://designcode.io/swiftui-advanced-handbook-compress-a-uiimage
아까 말씀드렸던 제가 참고한 레퍼런스입니다!
그리고 말했던것처럼 압축퀄리티를 0으로 해도 사이즈자체를 조절해 저장한것보다 3배정도 커서요, 데이터가 다 서버를 차지하는것이니 줄이면 줄일수록 좋다는 의견입니다~

2022-11-25 10:46 UTC, kelly1422 commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +
[2fd3754](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/2fd3754c07bfe8372934b9ff6fa811f753dbaabd)
적용완료!

2022-11-25 10:46 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
>              guard let image = coverPickerView.getImageView() else { return completion(nil) }
[2fd3754](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/2fd3754c07bfe8372934b9ff6fa811f753dbaabd)
적용완료!

2022-11-25 10:48 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
>          if !coverPickerView.getIsDefaultImage() {
[13f6b06](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/13f6b0664e14a95cf5bff86af1786b255ead3291)
적용완료!

2022-11-25 10:48 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/Component/PhotoPickerView.swift
> +    }
[13f6b06](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/13f6b0664e14a95cf5bff86af1786b255ead3291)
적용완료!

2022-11-25 10:52 UTC, kelly1422 commented on Vegeting/Global/Manager/FirebaseStorageManager.swift
> +
[6b4efbf](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/6b4efbf9b266cb053bbd1aa0f48053790c283880)
적용완료!

2022-11-25 13:29 UTC, yudonlee commented on Vegeting/Global/Extensions/UIImage+Extension.swift
> +    }
레퍼런스보다는 제로가 해당 코드의 동작원리를 알고 사용하셨는지 여쭤보고 싶습니다~~! 해당 사이트에서 사용했다고 해서 그걸 믿고 우리의 코드에 적용하는걸 원하지 않는거 같아요.. 테스트 결과 30KB, 300KB로 꽤 많이 줄여주는 건 확인했습니다. 
또한 해당 reference에서는 UIGraphicsImageRenderer를 사용하여 이미지 렌더링을 다시 했었고, 이는 우리 UIImage+ Extension에 존재하는 resize가 담당하고 있습니다. 해당 코드는 저또한 동작원리를 충분히 이해할수 있어서 쓰는데 납득이 갈거 같습니다. 혹시 resize로 바꾸시는 건 어려울까요? 
```suggestion
    var scaledToSafeUploadSize: UIImage? {
        let maxImageSideLength: CGFloat = 480
        let largerSide: CGFloat = max(size.width, size.height)
        let ratioScale: CGFloat = largerSide > maxImageSideLength ? largerSide / maxImageSideLength : 1
        let newImageSize = CGSize(width: size.width / ratioScale, height: size.height / ratioScale)
        
        return self.resize(to: newImageSize)
    }
    
    // 이미지를 입력받은 size에 맞춰 조절
    private func image(scaledTo size: CGSize) -> UIImage? {
        defer {
            UIGraphicsEndImageContext()
        }
        
        UIGraphicsBeginImageContextWithOptions(size, true, 0)
        draw(in: CGRect(origin: .zero, size: size))
        
        return UIGraphicsGetImageFromCurrentImageContext()
    }
```

2022-11-25 19:08 UTC, kelly1422 commented on Vegeting/Global/Extensions/UIImage+Extension.swift
> +    }
네 저는 이해했다고 판단하고 작성한 코드가 맞습니다, 어느부분에서 제가 이해를 못했다고 생각하시는걸까요~?
그리고 어느정도 이해를 한뒤에 저희 프로젝트에 도움이 되는 레퍼런스는 응용하는것이 나쁠게 없다고 생각하는데..😂 
직접 작성하지 않은 코드를 지양하더라도 저는 데이터 크기를 줄이는 것이 필요하다 생각해 이해하고 사용한 코드입니다! 이해가 안가시는 부분이 있다면 구체적으로 질문해주세요
그리고 resize가 저는 보이지 않아서요, 같은 역할을 해주는 resize가 있다면 그걸로 바꾸도록 하겠습니담 어디있는거죠!? 기본으로 제공해주는건 아닌거 같운데..

2022-11-27 05:39 UTC, yudonlee commented on Vegeting/Global/Extensions/UIImage+Extension.swift
> +    }
아무래도, 처음에는 작성 코드와 레퍼런스에서 그대로 가져온 코드가 있다보니, 전체적인 코드 흐름이나 사용목적을 전반적으로 듣고 싶었는데 다른 질문에 가려졌던거 같네여.UIImage+Extension에 데이크가 작성해둔게 있어서 참고하시길 바래요~!

2022-11-27 07:07 UTC, yudonlee commented on Vegeting/Global/Extensions/UIImage+Extension.swift
> +    }
q;
defer를 쓰신 목적이 무엇인지 궁금합니다. defer를 통해서 반드시 함수의 마지막에 실행되어야 하는 함수일까요?
defer키워드를 쓰는 곳이 생소하다 보니 궁금합니다.
q;
제로가 구현한 UIGraphicsBeginImageContextWithOptions도 이미지 리사이징이 가능하고, UIImageRenderer이라는 비교적 iOS10부터 지원되는 이미지 리사이징 기능이 추가되었습니다!
해당 기능에 대한 장점을 말하자면 기존 UIGraphicsBeginImageContextWithOptions는 UIImage를 srgb 영역에 맞추어서 redering하고 해당 크기는 pixel당 4byte입니다. iOS에서 지원하는 image format은 한 pixel당 1byte부터 8byte까지 다양하며, 이를 automatically하게 적용시켜주는 기능을 위해 등장한게 UIGraphicsImageRenderer입니다. 따라서 메모리를 최적화해서 image를 rendering하는 UIGraphicsRenderer를 사용한 UIimage+Extension의 resize를 쓰면 더욱 좋을거 같습니다~!
WWDC에서도 UIGraphicsBeginImageContextWithOptions를 사용하지 말고, UIGraphicsImageRenderer를 권장하고 있습니다. 감사합니당

## 출처 
https://developer.apple.com/videos/play/wwdc2018/416

2022-11-28 04:13 UTC, kelly1422 commented on Vegeting/Global/Extensions/UIImage+Extension.swift
> +    }
defer는 코드 실행 뒤 마지막에 꼭 실행시켜줘야 하는 함수는 저렇게 쓰는게 좋은것 같아서 저렇게 작성해보았습니다,!
resize를 사용해 적용했습니다~!!
[eef9b65](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/141/commits/eef9b65fa9826bf690d8d991d872369893da7b17)

2022-11-28 04:54 UTC, yudonlee approved these changes

2022-11-28 08:10 UTC, merged