[FEAT]: 프로필 설정 5번째 뷰를 구현합니다.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #143
Opened 2022-11-18 02:20 UTC by ccdkk

## 🌱 관련 이슈
- Close #80 

## 🌱 구현/변경 사항 및 이유
- 프로필 설정 5번째 뷰를 구현했습니다.
- 기존의 InterestView의 entryPoint를 구현하여 myProfile에서 사용할 때(선택 불가능), profile 등록 (선택 가능)을 구분하였습니다.

## 🌱 PR Point

## 🌱 참고 사항
![Simulator Screen Recording - iPhone 13 - 2022-11-18 at 11 20 22](https://user-images.githubusercontent.com/91456952/202601854-8516c33a-6b91-4651-8f6f-13ba72fece7e.gif)

2022-11-18 06:28 UTC, wonhui-kim reviewed
수고하셨습니다 ~~ 😁

2022-11-18 12:10 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserInterestViewController.swift
> +        button.addTarget(self, action: #selector(makeProfile), for: .touchUpInside)
와! 큰일 날뻔 했군요 예리한 지적 감사합니다! [5d928be](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/5d928be22ce100c9fdd5800cf8c383e033eccb43)에서 반영했습니다!

2022-11-18 12:11 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserInterestViewController.swift
> +    }
훨씬 좋은 것 같아요! TODO 잘 활용해 보겠습니다. [5d928be](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/5d928be22ce100c9fdd5800cf8c383e033eccb43)에서 반영완료!

2022-11-20 05:54 UTC, wonhui-kim approved these changes
수고하셨습니다~~

2022-11-20 08:39 UTC, yudonlee requested changes
데이크 수고많으셨습니다.   
참고사항이나, 수정해야할 사항들이 많아서 더욱 즐겁게 리뷰 보시며 알찬 공부 하셨으면 좋겠습니다. 
커스텀으로 구현하는 것도 좋지만, 애플이 만든걸 쓰는게 아무래도 가독성이나, 성능 측면에서 좋다보니 열심히 적어드렸네요.
개인적인 의견으로는 InterestView를 재사용하는게 좋은 구현인것은 분명하나, button의 액션들을 delegate로 전달하는 등 불편한 점이 있을거 같아 뷰를 나누시는 것도 조심스럽게 추천드려봅니다.😁

2022-11-20 08:39 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/Cell/InterestCollectionViewCell.swift
> +
p2;
데이크 예전에 말씀드렸던 CollectionViewCell에 내장된 override변수인 isSelected를 소개시켜 드릴게요!
해당 변수는 collectionView를 위해서 애플이 만들어 둔 기능으로서, 선택될 시 해당 변수의 값이 바뀌게 됩니다.!
```suggestion
override var isSelected: Bool {
        didSet {
            applySelectedState()
        }
    }
```

2022-11-20 08:39 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/Cell/InterestCollectionViewCell.swift
> +        interestLabel.font = isSelectedCell ? .preferredFont(forTextStyle: .subheadline, compatibleWith: .init(legibilityWeight: .bold)) : .preferredFont(forTextStyle:.subheadline)
p1;
위와 같은 방식으로 하게 됐을 때 이렇게 적용될 수 있습니다! ~~ 😁
```suggestion
      backgroundContentView.backgroundColor = isSelected ? .black : .systemGray6
        interestLabel.textColor = isSelected ? .white : .black
        interestLabel.font = isSelected ? .preferredFont(forTextStyle: .subheadline, compatibleWith: .init(legibilityWeight: .bold)) : .preferredFont(forTextStyle:.subheadline)
```

2022-11-20 08:39 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserInterestViewController.swift
> +                                      padding: UIEdgeInsets(top: 11, left: 20, bottom: 0, right: 20))
p2; 
앞서 설명드렸듯, 한 뷰에 height로 고정되는 것보단 최하단 버튼의 topAnchor를 기준으로 레이아웃을 잡으면 더욱 좋을것 같습니다.
```suggestion
selectInterestView.constraint(top: titleLabel.bottomAnchor,
                                      leading: view.leadingAnchor,
                                      bottom: profileRegisterButton.topAnchor,
                                      trailing: view.trailingAnchor,
                                      padding: UIEdgeInsets(top: 11, left: 20, bottom: 0, right: 20))
```

2022-11-20 08:39 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
>          let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
p1;
밑과 같이 allowMultipleSelection이라는 변수를 true로 바꿔주게 되면 collectionView에서도 다수의 것들을 선택할 수 있게 됩니다!
```suggestion
        let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
        collectionView.allowsMultipleSelection = true
```

2022-11-20 08:39 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +            return
q;
전에, break와 return의 차이가 궁금하시다고 하셔서 알려드립니다!
return같은 경우는, 해당 함수를 정상적으로 종료시키고 반환값을 반환하겠다는 의미를 가진 명령어입니다.    
해당 명령어는 함수를 "종료"시키고, "값"을 반환하는데 목적이 있기 때문에 현재 Delegate method의 경우 void 리턴값이기 때문에 문제가 발생하지 않지만, 다른 함수들의 경우 원치않는 결과 혹은 컴파일이 되지 않을 수 있습니다.

따라서 switch내에서는 break를 사용해주시고, 만약 switch 다음 구문이 실행될 필요가 없다면 값을 리턴하셔도 좋을것 같습니다!

2022-11-20 08:39 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +extension InterestView: UICollectionViewDelegate {
```suggestion
p1;
didSelect 함수를 통해서, local 변수에 등록된 개수 체크나, 삭제될 경우 해당 index를 찾는등 별도의 시간 리소스를 잡지 않고도 해결하능한 방법입니다!
위와같이 구현할 경우 selected한 cell의 개수를 통해서 더 select할 수 있을지 말지를 결정하는 UICollectionView의 Delegate Method입니다!

extension InterestView: UICollectionViewDelegate {
func collectionView(_ collectionView: UICollectionView, shouldSelectItemAt indexPath: IndexPath) -> Bool {
        if let count = collectionView.indexPathsForSelectedItems?.count, count >= 3 {
self.selectedInterestList = indexes.map {
                return interestList[$0.item]
            }
            delegate?.setBottomButtonEnabled(selectedList: self.selectedInterestList)
        }
        return collectionView.indexPathsForSelectedItems?.count ?? 0 <= 2
    }
```

2022-11-20 08:39 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
만약 위의 delegate method를 사용할 경우 해당 구문자체를 사용하지 않아도 가능합니다!
후에, 값을 전달하는 경우 UserInterestViewController의 button action을 InterestView가 전달받아 필요한 값을 전달하는 형태로 한다면, 계속해서 값이 바뀔떄마다 SuperView에 delegate로 넘기지 않아도 될 것 같습니다. 
```suggestion
```

2022-11-20 11:24 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +        interestCollectionView.constraint(.heightAnchor, constant: 139)
오 정말 값진 교훈입니다..autoLayout에 대한 이해가 부족했던 것 같아요. 우선 height를 뷰 내부에서 준 점은, 뷰컨 내에서 뷰를 위에서부터 차곡차곡 쌓는 것에 익숙해져서 collectionView에 bottomAnchor를 줄 생각을 못했던 것 같습니다. 그래서 bottomAnchor를 설정하지 않았을 때 collcetionView에 ambiguous height가 떠서 이를 해결하기 위해 고정 높이값을 줬던 것 같습니다. 좀더 유연히 대응할 수 있는 view를 구현하기 위해서는 autoLayout에 대한 이해가 더 필요하겠군요! 해당 내용들 [bd3b3b1](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/bd3b3b1c8b5b30c85530216c50174519e7eb7fd9)에서 반영하였습니다!

2022-11-20 12:00 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +        let width = interestList[indexPath.item].size(withAttributes: [.font : UIFont.preferredFont(forTextStyle: .subheadline)]).width + 50
carousel 디자인이 좌우 간격이 25씩이였기 때문에 50을 줬습니다. 이거를 40으로 바꾸면 보내주신 부분처럼 UI적인 면에서는 해결이 되지만 디자인 요구사항을 반영하지 못하게됩니다. 일단 뷰가 이렇게 그려지는 이유는 내가 지정한 item간의 spacing보다 커지는 것 때문이었습니다. 이는 UICollectionViewFlowLayout이 collectionView를 그리는 방법과 관련이 있었습니다.
<img width="702" alt="스크린샷 2022-11-20 오후 8 44 03" src="https://user-images.githubusercontent.com/91456952/202900108-9825ed52-e19d-4c86-97e7-bc28c3d0b90c.png">
FlowLayout은 위의 그림과 같은 방법으로 cell을 그려줍니다. 우리가 설정한 `layout.minimumInteritemSpacing` `layout.minimumLineSpacing`와 cell의 크기를 이용하여 collectionView의 width에 얼마나 많은 cell이 들어갈 수 있는지 결정한 후 해당 개수만큼 cell을 배치합니다. 이 때 생기는 빈공간을 spacing으로 채워버립니다. 메소드의 이름에도 나와있든 minimum값이기 때문에 이 spacing을 재조정하여 collectionView에 딱 맞게 배치를 하는 것 같습니다. 닐이 올려주신 두 번째 사진에서도 첫, 두번째 줄과 3번째줄의 spacing이 다른 것도 이에 따른 것 같습니다. 그럼 3번째 줄도 collectionView에 맞게 spacing이 늘어나야 하는 것 아니야? 라고 했을 때 이건 제 추측이지만 해당 빈공간에 어떤 크기의 cell이 들어올지 모르니  spacing을 minimum으로 유지하는 건가? 싶습니다.. 뇌피셜.. 네 이러한 문제들도 FlowLayout에는 fixed spacing을 주기가 어렵습니다.
그래서 UICollcetionVIewCompositionalLayout을 적용하였습니다. 여기서는 `NSCollectionLayoutGroup`에 `interItemSpacing = .fixed(12)`으로 고정된 값을 부여할 수 있더라구요. compostionalLayout을 쓰는 이유중 하나가 이 부분에도 있는 것 같습니다. 
해당 내용을 [bd3b3b1](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/bd3b3b1c8b5b30c85530216c50174519e7eb7fd9)에서 적용하였습니다!

Ref: https://developer.apple.com/library/archive/documentation/WindowsViews/Conceptual/CollectionViewPGforIOS/UsingtheFlowLayout/UsingtheFlowLayout.html

2022-11-20 12:04 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
>          let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
제가 isSelectedCell을 이용해서 구현했던 이유가 여러개가 선택이 안되었기 때문인데 요런게 있었네요!! 이게 있으면 굳이 사용할 필요가 없는 것 같습니다! `allowsMultipleSelection` 좋은 키워드 배워갑니다!!

2022-11-20 12:07 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +extension InterestView: UICollectionViewDelegate {
와 이것도 처음 알았네요 ㅋㅋㅋ 애플은 생각보다 많은 API를 제공해주고 있군요!! 이를 활용하면 가독성도 높고 순도 있는  코드가 될 것 같습니다. 바로 적용 해볼게요 🤩

2022-11-20 14:25 UTC, ccdkk commented
@yudonlee 
[f25642e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/f25642e9e854c1afa40d2ecf8461b3c42ed4e218)에서 적어주신 방법으로 적용해 보았습니다. 샘플로 적어주신 코드는 select을 하는 상황에서는 제대로 작동하나, deselect을 하는 상황의 대응이 없어서 이를 추가하여 구현하였습니다. 
[49e3ecf](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/49e3ecf2735dfffdb647012b0919a0592e5a9787) 확인 부탁드려요!

2022-11-22 10:29 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +        let width = interestList[indexPath.item].size(withAttributes: [.font : UIFont.preferredFont(forTextStyle: .subheadline)]).width + 50
추측이 맞을것 같습니다. 
## 가설 
1. cell item간 space가 minimum보다 클 때
첨부해주신 문서를 살펴보며 "If there is extra space at the end of the line, the layout object increases the interitem spacing until the items fit evenly within the line boundaries, as shown in Figure 3-3. Increasing the spacing improves the overall look of the items and prevents large gaps at the end of each line."을 통해서 last line들을 제외한 것들은 minimum line spacing이 존재하더라도 fit하기 위해 더욱 size가 클수 있다고 적혀있네요.

2. last row만은 그 대상에서 제외되는 이유 
첨부하신 애플 문서에서 "During layout, the flow layout object adds items to the current line until there is not enough space left to fit an entire item. If the line is just big enough to fit an integral number of items with no extra space, then the space between the items would be equal to the minimum spacing"이라고 되어있는데 
- 이것의 의미는 전체 아이템을 넣기에 충분하지 않을때 까지 item을 넣는다.
- 만약 추가 공간 없이도 해당 아이템들을 충분히 수용할 수 있다면 minimum spacing을 유지한다. 

## 결론
가설에서 1,2를 종합할 때 일단 last line은 아이템을 다 넣을수 있는 상태에서 공간마저 있다면 minimum spacing으로 준다. 그 이전 line들은 해당 line의 공간이 크다면 minimum 보다 더 크게 사이즈를 제공한다.

2022-11-22 11:40 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/InterestCollectionViewCell.swift
> +
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/f25642e9e854c1afa40d2ecf8461b3c42ed4e218#diff-621530c17340448afe600a661e652bcb33b97219af1cb0be72054c53c0783a11R29-R33에서 반영하였습니다.

2022-11-22 11:43 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/InterestCollectionViewCell.swift
> +        interestLabel.font = isSelectedCell ? .preferredFont(forTextStyle: .subheadline, compatibleWith: .init(legibilityWeight: .bold)) : .preferredFont(forTextStyle:.subheadline)
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/f25642e9e854c1afa40d2ecf8461b3c42ed4e218#diff-621530c17340448afe600a661e652bcb33b97219af1cb0be72054c53c0783a11R69-R71
에서 반영하였습니다

2022-11-22 11:46 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserInterestViewController.swift
> +                                      padding: UIEdgeInsets(top: 11, left: 20, bottom: 0, right: 20))
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/bd3b3b1c8b5b30c85530216c50174519e7eb7fd9#diff-89d6cca1f922df5bb84a005179dc6e5226607c666cb6d1237b4e97ec87a2458bR66
에서 반영완료!

2022-11-22 11:49 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
>          let collectionView = UICollectionView(frame: .zero, collectionViewLayout: layout)
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/f25642e9e854c1afa40d2ecf8461b3c42ed4e218#diff-6a6bccd0ca2b0fd81a525b987ade6ff6fce7b9f9db21ec2cdeba4f6f75abe205R44
에서 반영완료~!

2022-11-22 11:49 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +            return
오호 이해가 되었습니다. return을 무턱대고 쓰는 것은 위험하겠군요!

2022-11-22 11:58 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +extension InterestView: UICollectionViewDelegate {
shouldSelectItemAt은 해당 cell 선택여부를 true false를 결정해주는 함수이므로 실행될 때 마지막으로 누른 cell은  `indexPathsForSelectedItems`에 포함되지 않습니다. 그래서 0, 1, 2개 일 때의 경우를 나눠서 반영하였습니다. 더 좋은 방법이 있다면 알려주세요! [f25642e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/f25642e9e854c1afa40d2ecf8461b3c42ed4e218)에서 반영 완료!

2022-11-22 11:59 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
[f25642e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/f25642e9e854c1afa40d2ecf8461b3c42ed4e218)이 부분에서 반영하였고, 여기에서의 코드 반복을 피하기 위해 [함수화](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/49e3ecf2735dfffdb647012b0919a0592e5a9787)하였습니다.

2022-11-23 01:33 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
>          }
q;
해당 로직은, Deselct하는 조건인데, Deselect에서는 false조건이 쓰일때가 있을까요?

2022-11-23 01:33 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +extension InterestView: UICollectionViewDelegate {
제생각엔, 해당 로직에서는 선택의 true or false만을 담당하고, VC에서 버튼을 눌렀을때 delegate의 data를 전달하는 로직이 있었으면 좋겠어요.

2022-11-23 02:18 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +extension InterestView: UICollectionViewDelegate {
따라서 collectionView shoudSelectItemAt Delegate method에서는 selected cell에 따른 true or false만을 담당합니다. 해당함수의 목적은 셀이 선택될지 안될지를 판단함수니까요. 
didSelctedItemAt, didDeselectItemAt 함수에서 button이 enable될지 disable될지 판단하는 함수를 호출합니다. 해당 함수에서는  button이 enable될지 말지 결정해서 delegate method를 호출시킵니다!

2022-11-23 10:40 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
>          }
[7c6bd1f](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/7c6bd1f0669ebb26442c9bf55eddf3480ced46a8)에서 반영하였습니다. 역할에 따라 코드 부여하는거 좋아요~!

2022-11-23 10:41 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +extension InterestView: UICollectionViewDelegate {
[7c6bd1f](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/7c6bd1f0669ebb26442c9bf55eddf3480ced46a8)에서 반영하였습니다~!

2022-11-24 08:26 UTC, yudonlee requested changes

2022-11-24 08:26 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
p1;
swift 문법상 허용되지만, 그래도 return을 명시해주시면 더욱 좋을거 같아요!

2022-11-24 08:26 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
p4;
해당 함수들의 paramter로 to, with를 쓰기보단 무슨 파라미터인지 명시해주는게 더욱 좋을 거 같아요!

2022-11-24 08:26 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
p3;
cell deselect를 막을 이유는 없어서 해당 코드는 삭제한다고 했던거 같은데, 어떤 이유로 넣으셨는지 알고 싶습니다!.

2022-11-24 08:26 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
p2;
comparisonValue가 무엇을 의미하는지 알기 어려울 거 같아요. (to등으로 하는건 가독성을 저하시킬 수 있는 거 같습니다!)
p4;
무엇과 비교한다는 걸까?라는 의문이 드는거 같아요.    
cell에 주는 action에 따라서 다른 비교방식을 쓰는걸 enum으로 바꿨을때 가독성이 더 좋은 것 같은데 어떠신가요?    
개인적인 기호인거 같아서, 그대로 두는게 나은거 같으면 반영하지 않으셔도 될 거 같아요.
```suggestion
   enum SelectType {
     case selectCell
     case deselectCell
     var buttonEnableQualify: Int {
       switch self {
       case .selectCell:
         return 0
       case .deselectCell:
         return 1
       
       }
     }
   }
    private func judgeSelectCellEnabled(type: SelectType) -> Bool {
        guard let selectedCellCount = interestCollectionView.indexPathsForSelectedItems?.count else { return true }
        if type.minimumQualify  <= selectedCellCount  && selectedCellCount <= type.minimumQualify  + 2 {
            return true
        } else {
            return false
        }
    }
```

2022-11-24 08:26 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
p1;
해당 부분도 return을 명시해주시면 더 좋을거 같아요!

2022-11-24 08:46 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
[928a059](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/928a059d2a276d56b9c06f7bb093e9005b2ced75)에서 함수화할 필요가 없어져서 반영되었습니다!

2022-11-24 08:49 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
comparisonValue는 명시해주는게 좋겠네요!
isEnabled의 경우에는 judgeBottomButtonEnabled(isEnbaled: true, comparisonValue: 1) 의 형태로 사용될 텐데 enabled의 불필요한 반복 처럼 느껴지는 것 같아요. enabeld가 true이기 위해 비교값으로 버튼의 enabled를 판단할 것이다 라는 맥락에서 to를 써봤는데 어색할까요?

2022-11-24 08:50 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
음 비교값이라는 의미로 사용했는데 더 적절한 표현이 있을까요? 일단 judgeSelectCellEnabled 함수는 사라져서 judgeBottomButtonEnabled에서 활용될 것 같습니다. targetValue? .. targetSelectedCellCount..?

2022-11-24 10:13 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
앗 까먹었네요! [928a059](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/928a059d2a276d56b9c06f7bb093e9005b2ced75)에서 삭제했습니다!

2022-11-24 11:22 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
적절해보이네요 ~~~

2022-11-24 11:23 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
ButtonStatus는 어색할까요?

2022-11-24 11:26 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
어떤게 적절하다는 건가용 targetValue, targetaSelectedCellCount, comparisonValue..?

2022-11-24 11:31 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
`judgeBottomButtonStatus(isEnabled: Bool)`말씀하시는 건가요?

2022-11-24 11:31 UTC, yudonlee commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
IsEnabled 대신입니다~~

2022-11-25 03:47 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
button은 함수 네임에 이미 button이라고 명시해줘서 없어도 될 것 같고 status는 괜찮은 것 같아요. 반영하겠습니다.

2022-11-25 04:32 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
[eb90478](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/eb90478b7cb92ce07cc6dcd8fb94d1f8398bc2d0) targetValue로 반영하였습니다.

2022-11-25 04:32 UTC, ccdkk commented on Vegeting/Global/UIComponent/InterestView.swift
> +    }
[eb90478](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/143/commits/eb90478b7cb92ce07cc6dcd8fb94d1f8398bc2d0)에서 반영하였습니다.

2022-11-25 04:51 UTC, yudonlee approved these changes
고생하셨습니다~

2022-11-25 05:32 UTC, merged