[FEAT]: 프로필 설정 페이지 중 채식 단계를 선택하고 한 줄 소개를 작성하는 페이지를 구현합니다.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #146
Opened 2022-11-20 05:58 UTC by wonhui-kim

## 🌱 관련 이슈
- #136 

## 🌱 구현/변경 사항 및 이유
### UserTypeIntroductionViewController
// 프로필 설정 4번째 단계. 채식 단계 선택 및 프로필 한 줄 소개를 작성할 수 있는 뷰

- 모달뷰(SelectVegetarianTypeViewController)에서 선택한 옵션을 해당뷰(UserTypeIntroductionViewController)의 버튼 타이틀로 변경하기 위해서 SelectVegetarianTypeViewDelegate 프로토콜을 conform했습니다.
- 프로토콜 내부 didSelectVegetarianType(type: String) 함수는 type을 받아와 버튼의 타이틀을 변경해주는 역할을 합니다.
- 프로토콜 내부 didSelectVegetarianTypeForNextButton() 함수는 선택이 완료되었다는 신호를 주어 다음 버튼이 활성화되도록 하는 역할을 합니다.
- 프로필 한 줄 소개 작성칸은 여러줄 입력을 위해 UITextView로 구현했고, 글자수 제한 및 현재 글자수를 표시해주기 위해 delegate 선언 후 textViewDidChange 함수를 사용하여 textView 변경 시 해당 함수가 호출됩니다.
      

### SelectVegetarianTypeViewController
// 채식 단계 선택 버튼을 눌렀을 때 모달 형식으로 보여지는 단계를 선택 가능한 TableView
- tableView의 delegate의 didSelectRowAt 함수를 통해 선택한 셀에 체크마크 표시를 했습니다.
- tableView의 delegate의 didSelectRowAt 함수를 통해 선택 완료 시 "완료" 버튼이 활성화됩니다.
- "완료" 버튼(completeButton) 을 누르면 호출되는 completeButtonTapped 함수에서 앞의 뷰에서 선언한 프로토콜 내부 delegate 함수 didSelectVegetarianType과 didSelectVegetarianTypeForNextButton을 호출합니다.

## 🌱 PR Point
- SelectVegetarianTypeViewDelegate 프로토콜 내부 함수명이 직관적인지 봐주시고, 더 나은 네이밍이 있으면 알려주세요~

## 🌱 참고 사항

<img width=300 src="https://user-images.githubusercontent.com/96123303/202887120-3d840586-b018-4a99-be14-db8fccb292f1.gif"/>

2022-11-20 16:57 UTC, ccdkk reviewed
고생하셨습니다~!

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +        button.setTitleColor(UIColor.vfYellow1, for: .normal)
p4;
setTitleColor끼리 붙여주면 더 읽기 쉬울 것 같아요!

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +    private lazy var vegetarianTypeTable: UITableView = {
q;
lazy로 선언해주신 이유가 궁금합니다~!

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +    }()
p2;
요 친구도 font 설정 부탁드려요!

2022-11-20 16:57 UTC, ccdkk commented on Vegeting.xcodeproj/project.pbxproj
>  			path = Component;
p2
viewController인데 component에 들어가 있어요!

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +            cell.accessoryType = .checkmark
오잉 이런 기본제공 메소드도 있군요.. 신기

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +        let model = TypeDescription(type: type.type, description: type.description)
p3;
type.type으로 되어있으니 뭔가 어색하게 느껴져서 구분을 주기 위해 파라미터를 typeName으로 수정하는 것은 어떤가요?

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/Component/VegetarianTypeTableViewCell.swift
> +class VegetarianTypeTableViewCell: UITableViewCell {
p2;
final 붙여주세요!

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/Component/VegetarianTypeTableViewCell.swift
> +        label.textColor = UIColor(hex: "#616161")
p2;
vfGray1 입니다 ~

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/Component/VegetarianTypeTableViewCell.swift
> +    public func configure(with model: TypeDescription) {
q;
public으로 접근제어를 해주신 이유가 있을까요?

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +        button.setTitle("\(vegetarianTypeSelectButtonTitle)", for: .normal)
p2;
` button.setTitle(vegetarianTypeSelectButtonTitle, for: .normal)`이렇게 써줘도 될 것 같아요!

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +        button.backgroundColor = UIColor(hex: "#F2F2F2")
p2;
vfGray4 입니다 ㅎㅎ

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +        button.setTitleColor(UIColor(hex: "#8E8E93"), for: .normal)
p2;
vfGray3입니다 ㅎㅎ

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +        textView.backgroundColor = UIColor(hex: "#F2F2F2")
p2;
vfGray4 입니다 ㅎㅎ

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +        label.textColor = UIColor(hex: "#8E8E93")
p2;
vfGray3입니다 ㅎㅎ

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +            progressBarImageView.topAnchor.constraint(equalTo: view.topAnchor, constant: view.frame.height * 1/10),
p5;
* 0.1을 해주는게 좀더 직관적일 수 있을 것 같아요.

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +    }
함수로 구분해주신 거 너무 좋네요!! 잘읽히는 것 같아요
notEditingTextViewForm 네이밍으로 applyEndEditingTextViewForm 추천합니다.
그리고 vfColor 적용 부탁드려요 ㅎㅎ..

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +class SelectVegetarianTypeViewController: UIViewController {
p2;
final 붙여 주세요!

2022-11-20 16:57 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +}
p2;
SelectVegetarianTypeViewController의 protocol 인 것 같은데 위치가 요기 있어서 어색한 것 같아요

2022-11-21 01:50 UTC, yudonlee requested changes
고생하셨습니다 메이! 
가독성이 좋은 코드가 많이 보여서 읽기 편했습니다. 그래도 다음엔 300 under를 지켜주시면 더 좋을거 같아요

2022-11-21 01:50 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +    private var selectedVegetarianType = ""
p3;
eum을 통해서 관리받는다면, enum type이겠네요 😁

2022-11-21 01:50 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +}
p3;
enum으로 관리하는 건 어떨까요? 해당 내용이 다른 View에서도 쓰일거 같고, enum을 통해서 가독성이나 재사용성을 높이면 더욱 좋을거 같습니다!
```suggestion
enum vegetarianType {
    case vegan
    // ...
    var description: String { 
       switch self {
       case .vegan:
       return "완전한 식물성만 섭취해요"
       }
    }
}
```

2022-11-21 01:50 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +        button.setTitleColor(UIColor.vfYellow1, for: .normal)
disable과 normal을 button 내에서 색깔로 선택해줄수 있는걸 몰랐습니다.. 감사합니다 최고!

2022-11-21 01:50 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +        }
가독성 좋게 잘 구현하신 것 같습니다.

2022-11-21 01:50 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +        let model = TypeDescription(type: type.type, description: type.description)
enum으로 변할경우 이부분도 수정이 필요할 것 같습니다~!

2022-11-21 01:50 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +    }
시뮬레이터 하면서 놀랬습니다! 너무 잘 구현하신 것 같습니다. 
저는 activate라는 Naming을 쓰는건 어떨까요?
```swift
func activateTextViewHighlight
func deActivateTextViewHighlight
```

2022-11-21 01:50 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +        ])
p2;
아무래도, TextView에 bottom Anchor를 추가로 주시거나, ScrollView등의 작업이 필요해보여요 🥲
![image](https://user-images.githubusercontent.com/39371835/202943732-3b3b6593-ab69-43c5-947a-3262baef2d10.png)
SE에서 깨지는 현상이 발견되네요

2022-11-21 07:27 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +            cell.accessoryType = .checkmark
accessoryType 말씀하시는 건가요?!
UITableView cell의 오른쪽 부분을 accessoryView라고 하더라구요! 
스토리보드 공부할 때 잠깐 봤었는데 저도 다시 사용하게 되었네요 😄

2022-11-21 07:49 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +            progressBarImageView.topAnchor.constraint(equalTo: view.topAnchor, constant: view.frame.height * 1/10),
이것 이외에 다른 constant들도 비율로 준 것들이 있는데, 
1/8, 1/25 등 대략적인 값을 계산해서 준 것들과의 통일성을 위해서 분수로 표현했습니다!

2022-11-21 08:01 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +        button.setTitleColor(UIColor.vfYellow1, for: .normal)
저도 이번에 제로가 만들어주신 글로벌 bottomButton에서 배웠습니당 😁

2022-11-21 08:01 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +        }
저번 pr에서 닐이 알려주신 함수 분리!! 잘 쓰고 있습니당😆

2022-11-22 06:47 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +        button.setTitleColor(UIColor.vfYellow1, for: .normal)
[반영](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-8115690f5ee5a5aa8a67ad31652f7b0a428ce01ab0989c1cd5e83c9a211cb61bR96-R97)했습니다~

2022-11-22 06:48 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +    private lazy var vegetarianTypeTable: UITableView = {
제가 착각을 했네요
이전 뷰컨트롤러에서 채식 단계 버튼을 누르면 연결되는 뷰(SelectVegetarianTypeViewController)가 따로 있는데,
기존 뷰에서 접근 시 생성된다고 생각해버렸어요 😅
해당 테이블뷰는 Select~ViewController 생성과 동시에 보이는 뷰인데 말이져!
[수정](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-8115690f5ee5a5aa8a67ad31652f7b0a428ce01ab0989c1cd5e83c9a211cb61bR103-R109)했습니다

2022-11-22 06:48 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +    }()
[설정](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-8115690f5ee5a5aa8a67ad31652f7b0a428ce01ab0989c1cd5e83c9a211cb61bR85-R87)했습니다~

2022-11-22 06:51 UTC, wonhui-kim commented on Vegeting.xcodeproj/project.pbxproj
>  			path = Component;
ViewController 폴더로 [이동](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-af5ceb9032e5d7f2f4974c5169c844b9fb32b14289eacbc7df75d48466d15d1aR657-R668)했습니다~

2022-11-22 06:53 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +        let model = TypeDescription(type: type.type, description: type.description)
동의합니다! 그러는 편이 더 좋을 것 같아요~
[반영](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-cff65fe87ac40561d8db62b597edd81f8fa0b5c961fdd3084d1e2db824ec6c56R202-R205)했습니다~

2022-11-22 06:54 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/VegetarianTypeTableViewCell.swift
> +class VegetarianTypeTableViewCell: UITableViewCell {
앗ㅎㅎ [수정](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-0ad06f66f861e461f37c0fb96efffb3ea3682bbff3de2cfd060336b5829063bdR9-R11)했습니다!

2022-11-22 06:54 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/VegetarianTypeTableViewCell.swift
> +        label.textColor = UIColor(hex: "#616161")
[수정](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-0ad06f66f861e461f37c0fb96efffb3ea3682bbff3de2cfd060336b5829063bdR22) 완료했습니다~

2022-11-22 07:01 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +        button.backgroundColor = UIColor(hex: "#F2F2F2")
[반영](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#) 완료 😆

2022-11-22 07:01 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +        button.setTitleColor(UIColor(hex: "#8E8E93"), for: .normal)
[반영](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-1edeadd9a272a190b8562f39aee8e642b3363ae408d845ec87e1fafb4d9a34b8R32) 완료 @

2022-11-22 07:02 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +        textView.backgroundColor = UIColor(hex: "#F2F2F2")
[반영](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-1edeadd9a272a190b8562f39aee8e642b3363ae408d845ec87e1fafb4d9a34b8R50) 완료~

2022-11-22 07:02 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +        label.textColor = UIColor(hex: "#8E8E93")
알려주셔서 감사합니다!
[반영](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-1edeadd9a272a190b8562f39aee8e642b3363ae408d845ec87e1fafb4d9a34b8R59) 완료~

2022-11-22 07:11 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +    }
컬러 [적용](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-1edeadd9a272a190b8562f39aee8e642b3363ae408d845ec87e1fafb4d9a34b8R150-R159)했습니다!

네이밍은 하단에 닐이 제안해주신 것처럼 해당 함수가 제공하는 기능에 집중하여 activateTextViewHighlight, deActivateTextViewHighlight 로 설정해보았는데 어떤가요?!

2022-11-22 07:11 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +class SelectVegetarianTypeViewController: UIViewController {
[수정](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-cff65fe87ac40561d8db62b597edd81f8fa0b5c961fdd3084d1e2db824ec6c56R78)했습니다!

2022-11-22 07:16 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +    }
해당 함수가 제공하는 기능에 집중한 네이밍 너무 좋다고 생각합니다!
[반영](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-1edeadd9a272a190b8562f39aee8e642b3363ae408d845ec87e1fafb4d9a34b8R150-R159)했습니다~

2022-11-22 07:32 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +}
해당 뷰(SelectVegetarianTypeViewController)의 작업을 대신해주는 부분이라 SelectVegetarianTypeViewDelegate로 네이밍했지만, 막상 해당 프로토콜을 채택하고 있는 부분은 UserTypeIntroductionViewController이고, 프로토콜의 함수가 구현되어야 할 곳은 UserTypeIntroductionViewController이기에 여기에 선언해주었습니다!

하지만 해당 delegate 프로토콜을 여러 뷰컨트롤러에서 쓰게될 경우에는 delegate 제공 주체인 뷰컨트롤러에서 해당 프로토콜을 선언해주는 편이 좋아보이네요!!
[수정](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-cff65fe87ac40561d8db62b597edd81f8fa0b5c961fdd3084d1e2db824ec6c56R73-R76) 했습니다 😄

2022-11-22 07:36 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/VegetarianTypeTableViewCell.swift
> +    public func configure(with model: TypeDescription) {
configure 함수 사용이 익숙하지 않아서 시행착오를 거치다 보니 해당 과정에서 수정되지 않은 부분이 남아있었네요 😊
[수정](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-0ad06f66f861e461f37c0fb96efffb3ea3682bbff3de2cfd060336b5829063bdR56-R59)했습니다~

2022-11-22 07:37 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +        let model = TypeDescription(type: type.type, description: type.description)
[수정](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-cff65fe87ac40561d8db62b597edd81f8fa0b5c961fdd3084d1e2db824ec6c56R201-R205)했습니다!

2022-11-23 11:59 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +    }
좋습니다!

2022-11-23 12:00 UTC, ccdkk approved these changes
고생하셨습니다!

2022-11-24 09:49 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +        ])
엇 미처 확인을 못했네요@!
9eb6bfcaba72ba7d713916127342afe1b6459535
반영했습니다!

2022-11-25 06:13 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/Component/SelectVegetarianTypeViewController.swift
> +}
좋은 의견 감사합니다!!
[반영](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/146/files#diff-cff65fe87ac40561d8db62b597edd81f8fa0b5c961fdd3084d1e2db824ec6c56R10-R44)해보았습니다~~

2022-11-28 07:25 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserTypeIntroductionViewController.swift
> +        ])
https://user-images.githubusercontent.com/39371835/204218050-37d44d62-9ee8-46b3-8605-7be14177c4ce.mp4
여전히 깨지는 문제가 발생하는 것 같습니다~!

2022-11-29 01:34 UTC, yudonlee approved these changes
고생 많으셨어요~!

2022-11-29 10:11 UTC, merged