[FEAT]: 유저 등록할 때 닉네임 중복 체크 로직
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #156
Opened 2022-11-21 10:58 UTC by kelly1422

## 🌱 관련 이슈
- close #123 

## 🌱 구현/변경 사항 및 이유
###  1. 유저 등록할 때 닉네임 중복 체크 api 작성
`isPossibleNickname(newName: String) -> Bool` 
매개변수로 String 값인 닉네임을 받아, 해당 닉네임이 사용 가능한 닉네임인지 (중복되는 닉네임이 없는지) 확인하고
사용 가능하면 true, 불가하면 false를 리턴해주는 함수입니다.

로직은 `whereField("userName", isEqualTo: newName)` 를 사용해, userName이 입력받은 매개변수 newName과 같은 데이터를 받아오고, 받아온 데이터가 비어있으면 중복이 아니므로 true, 비어있지 않으면 중복이므로 false를 반환해주는 로직입니다.

## 🌱 PR Point
더 좋은 방법이 있다면 말씀해주세요

## 🌱 참고 사항
아래 테스트해본 결과 캡처해서 올립니다! 
Test는 이미 존재하는 user라 불가능이 출력되고 Test11은 중복이 없어 가능이 출력되고 있습니다.
<img width="550" alt="스크린샷 2022-11-21 오후 7 49 34" src="https://user-images.githubusercontent.com/80809782/203033425-fbb18400-50f9-47df-aa12-06fabbde5ca4.png">
<img width="550" alt="스크린샷 2022-11-21 오후 7 50 00" src="https://user-images.githubusercontent.com/80809782/203033442-41ae7bd5-ddc8-4b42-b17d-a70b752327aa.png">

2022-11-23 04:54 UTC, ccdkk approved these changes
멋지군요! 고생하셨습니다.

2022-11-23 05:01 UTC, yudonlee requested changes
고생하셨어요 제로~~!

2022-11-23 05:01 UTC, yudonlee commented on Vegeting/Global/Manager/FirebaseManager.swift
>  }
async를 쓰셔서 잘 구현하신 것 같습니다. 다만 async throw까지 사용해서 error상황은 error로 전달하는 건 어떤가요?
저또한 그렇게 구현을 점차 바꿀 예정입니다. !

2022-11-23 15:48 UTC, kelly1422 commented on Vegeting/Global/Manager/FirebaseManager.swift
>  }
[f0b917e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/156/commits/f0b917e4fa85a8332ee3cf2ea0cbcb6817500bb8)
적용해보았습니다!

2022-11-24 09:46 UTC, yudonlee commented on Vegeting/Global/Manager/FirebaseManager.swift
>  }
아주 좋습니다!

2022-11-24 09:46 UTC, yudonlee approved these changes
고생많으셨어요~!

2022-11-24 11:22 UTC, merged