[FEAT]: 모임글 상세화면에 해당 모임 정보를 띄워줍니다.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #159
Opened 2022-11-21 13:53 UTC by kelly1422

## 🌱 관련 이슈

## 🌱 구현/변경 사항 및 이유

## 🌱 PR Point

## 🌱 참고 사항

2022-11-27 07:22 UTC, yudonlee commented on Vegeting/Screens/GroupList/Component/ClubListCollectionView.swift
> +        let detailViewController = PostDetailViewController(club: clubList[indexPath.item])
p5; 
해당 viewController가 무엇인지 분명하게 나타내주는건 어떨까요?~~ 
```suggestion
        let postDetailViewController = PostDetailViewController(club: clubList[indexPath.item])
```

2022-11-27 07:39 UTC, yudonlee commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        }
q;
1. closure내부에서 self를 호출하지 않는데 Task에 weak self를 붙여주신 이유가 있을까요?
2. FireStorageManager는 escaping closure을 사용하는 함수인데, Task는 concurrency context가 아닌 함수 내부에서 concurrency context하게 만들어주는 클로저라 용도가 다른데 사용하신 이유가 있을까요?
p3;
클로저 내부에서는, 해당 imageView의 속성을 설정하는 구문만 사용하고 image를 불러오기 위한 작업들은 
따로 함수화해서 viewDidLoad때 호출하는건 어떨까요?
p4;
guard let을 통해서 if let 내부에서 실행하는것보다 depth가 적은것 처럼 보이는데, 그대신 else구문에 return을 해줘야 한다는 조건이 있습니다. 따라서 if let과 else로 나눠서 하면 가독성이 조금더 좋아보이는데 어떨까요? 취향차이라 depth가 길어지는게 싫으시다면 else에 return을 추가해주시고, 아니라면 저처럼 해도 좋을거 같아요! 편하신 걸 골라주세요~~
```swift
private func setCoverImageView() {
        if let url = self.club.coverImageURL{
            FirebaseStorageManager.downloadImage(url: url) { [weak self] image in
                self?.coverImageView.image = image
            }
        } else {
            coverImageView.image = UIImage(named: "coverImage")
        }
    }
```

2022-11-27 08:24 UTC, yudonlee requested changes
안녕하세여 제로! 개인의 취향인 리뷰도 있고,  반영하면 좋을것 들도 적어두셨으니 참고 바랍니다😁 고생하셨습니다~!

2022-11-27 08:24 UTC, yudonlee commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        super.init(nibName: nil, bundle: nil)
super.init에서 nib 파일등을 nil로해서 custom initializer를 하는 방법이 있군요! 
평소 custom initializer는 convenience init으로만 가능한 줄 알았는데 새롭게 배웠네요.

2022-11-27 08:24 UTC, yudonlee commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        contentView.widthAnchor.constraint(equalTo: scrollView.widthAnchor).isActive = true
p5;
밑에 함수들은 extension을 쓰지 않아서, 혹시 통일하는건 어떨까요?
아무래도 extension의 단점은 width등을 분리해서 쓰는거인데, 그것보다 밑에서 구현된거 같이 top, leading, width, height등을 한 array 내부에 넣고 activate하는게 가독성이 좋은거 같아서요~ 유지보수할때도 한번에 확인 가능하고!

2022-11-28 08:09 UTC, kelly1422 commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        contentView.widthAnchor.constraint(equalTo: scrollView.widthAnchor).isActive = true
[2773aa5](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/159/commits/2773aa59eceb3975c608347d5b0f2b4ddb55e9e9)
통일했습니다!!

2022-11-28 08:10 UTC, kelly1422 commented on Vegeting/Screens/GroupList/Component/ClubListCollectionView.swift
> +        let detailViewController = PostDetailViewController(club: clubList[indexPath.item])
[f5c6363](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/159/commits/f5c6363df18e6a2f30e841c6d6c7da8a7d40cc69)
동의합니다~ 그래도 비슷하게 적는다고 앞에 detail붙이긴 했는데 .. 역시 정확하게 적는게 좋죠! 적용완료

2022-11-29 04:17 UTC, kelly1422 commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        }
오호 이렇게 코드를 작성했었네요
[294d11f](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/159/commits/294d11f6f893befbe4821342050e29b2830bca08)
지금 사진 띄우는 방법을 kingfisher 사용한걸로 수정해서 디벨롭에 머지해놓은 상태라
디벨로 머지후 해당 방법으로 수정하였습니다!

2022-11-29 08:04 UTC, yudonlee approved these changes
고생하셨어요~!

2022-11-29 09:16 UTC, merged