[FEAT] 모임개설뷰 폴더링을 진행했습니다.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #16
Opened 2022-10-22 08:18 UTC by ccdkk

## 🌱 관련 이슈
- Close #12 

## 🌱 구현/변경 사항 및 이유
- 폴더가 겹치는 것을 방지하기 위해 미리 폴더링을 해뒀습니다.

## 🌱 PR Point

## 🌱 참고 사항

2022-10-22 11:52 UTC, yudonlee requested changes

2022-10-22 11:52 UTC, yudonlee commented on Vegeting.xcodeproj/project.pbxproj
> +			sourceTree = "<group>";
p3; 
데이크 VC라는 축약어도 좋지만, 
```
Controllers
```
와 같은 분명한 표현은 어떤가요?

2022-10-22 12:22 UTC, wonhui-kim approved these changes
겹침 방지 좋습니다!

2022-10-22 13:14 UTC, ccdkk commented on Vegeting.xcodeproj/project.pbxproj
> +			sourceTree = "<group>";
동의합니다! 그러면 ViewController 라고 하는건 어떠신가요? ViewModel과 통일성을 맞추기 위함입니다.

2022-10-23 00:29 UTC, yudonlee commented on Vegeting.xcodeproj/project.pbxproj
> +			sourceTree = "<group>";
네 좋습니다

2022-10-23 05:11 UTC, ccdkk commented on Vegeting.xcodeproj/project.pbxproj
> +			sourceTree = "<group>";
[592ee63](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/16/commits/592ee633b2249c7d00f8493be8267ebfe2edfdb8)에서 반영하였습니다.

2022-10-23 05:42 UTC, yudonlee approved these changes

2022-10-23 05:43 UTC, merged