[FEAT]: PostDetailViewController에 들어갈 때 내가 작성한 글인지 구분하여 button, actionSheet에 변화를 줍니다.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #164
Opened 2022-11-24 09:22 UTC by ccdkk

## 🌱 관련 이슈
- Close #155 

## 🌱 구현/변경 사항 및 이유
- PostDetail에 entryPoint를 mine과 other로 나누어 actionSheet에 변화를 줍니다.
- PostDetail에 entryPoint를 mine과 other로 나누어 button의 enabled를 결정합니다.
- verticalAlignLabel이 더 이상 필요하지 않아 관련내용을 삭제했습니다.
- 본인의 게시물에서 수정하여 들어가면 club의 정보들을 default값으로 제공합니다. datePicker와 location값을 넘기는 부분에서는 별 문제가 없었으나 collectionView의 default값을 넘길 때 트러블 슈팅이 있었습니다. 현재 select된 cell의 layout 변경을 아래처럼 isSelected를 override 하여 사용하고 있습니다.
```Swift
 override var isSelected: Bool {
        didSet {
            applySelectedState()
        }
    }
```
그래서 cell을 return해주는 부분에서 선택된 카테고리의 index인 경우 isSelected = true로 줘서 이를 구현하여 했었습니다.
```Swift
  func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: GroupCategoryCollectionViewCell.className, for: indexPath) as? GroupCategoryCollectionViewCell else { return UICollectionViewCell() }
    
        if let selectedCategory = self.selectedCategory {
            let index = categoryList.firstIndex(of: selectedCategory)
            if index == indexPath.item {
                cell.isSelected = true // 처음에 시도한 방법
//                categoryCollectionView.selectItem(at: indexPath, animated: true, scrollPosition: .bottom)
            }
        }
        cell.configure(with: categoryList[indexPath.item])
        return cell
    }
```
그런데 cell의 isSelected가 자동으로 false로 초기화 되더라구요. 
<img width="348" alt="스크린샷 2022-11-24 오후 6 06 58" src="https://user-images.githubusercontent.com/91456952/203741912-a2c8ca54-4b2f-4a28-99e7-b33df1551f71.png">
그래서 apple 문서에 UICollectionViewCell isSelected를 보니, isSelected값을 직접적으로 바꾸지 말고 selection Method인 `selectItem`을 사용하라고 나와있습니다.
<img width="718" alt="스크린샷 2022-11-24 오후 6 03 05" src="https://user-images.githubusercontent.com/91456952/203740214-2dd1926b-57a3-4974-ad83-f6b1496bea27.png">
<img width="613" alt="스크린샷 2022-11-24 오후 6 09 23" src="https://user-images.githubusercontent.com/91456952/203743007-17858fbf-7e2f-4db7-be27-264204e6f507.png">
이를 통해 selection을 줬더니 의도한대로 default값이 들어가더라구요! 
네 그랬습니다.. 이와 관련해서 블로그를 찾아봤는데 `isSelected에 직접적으로 값을 주지 마라`라는 멘트가 UICollectionView에만 있다네요? UITableView를 확인해본 결과 요런 멘트는 없었습니다. 왜 UICollectionView만 그럴까요? 참 요상하네요. 더 알아보고 싶었으나 갈길이 멀어.. 더 알아보지 못해 아쉽네요! 여유로울 때 깊게 알아보겠습니다.
Ref:
https://developer.apple.com/documentation/uikit/uicollectionviewcell/1620130-isselected/
https://eunjin3786.tistory.com/461

## 🌱 PR Point
- entryPoint의 네이밍이 적절한가요?
- AuthManaer가 init될 때 current User의 정보를 AuthManager 내부 프로퍼티로 저장하는게 적절할까요?

## 🌱 백로그
- 신고, 차단, 탈퇴, 삭제 관련한 firebase 코드가 아직 없어서 연결하지 않았습니다. 아마 없는 것 같아서 저희 피그잼 백로그에 써놨습니다. 누가 구현할지 정해보면 좋을 것 같아요.. 신고는 단순할 것 같은데 차단: 차단한사용자 게시물 목록에서 삭제 + 같이 있는 채팅방..?, 탈퇴: 탈퇴코드 + 탈퇴한 사용자 게시글 삭제 + 채팅방 삭제, 삭제: club, participated club, chat방은 어떻게..? 등등 생각해야할 부분들이 많은 것 같아요

## 🌱 참고 사항
![Simulator Screen Recording - iPhone 13 - 2022-11-24 at 18 16 06](https://user-images.githubusercontent.com/91456952/203744547-fa71e2ab-07f5-462e-a3c8-bf390bf94843.gif)

2022-11-27 12:24 UTC, yudonlee requested changes
## 리뷰 후기
안녕하세요 데이크~~ 놓친 부분이 조금 보여서 하나둘씩 쓰다보니 엄청 많은 코멘트가 되어버렸네요..후후
데이크가 엄청 좋아하실것 같습니다~! isSelected에서 출발해서 selectItem으로 도달한 과정이 정말 흥미롭네요. 애플 document를 통해 성장하는 데이크를 보니 좋습니다.    
isSelected는 아무래도 getter의 성격으로서 우리가 해당 값을 설정할 수 없도록 하는게 맞는것 같습니다. 우리가 해당 셀을 선택하고 싶다면, cell swift 파일이 아닌, 외부 collectionView에서 해당 아이템을 선택하도록 하는게 더 가독성이 좋고 별도의 로직처리가 간단하기 떄문이라고 추측합니다. (ex. 3번 셀이 선택되기 위해서는 collectionView를 갖고 있는 VC에서 selectItem을 하는게, 셀내부에서 특정 조건을 줘서 isSelected값을 바꾸는 것중 전자가 더 간단하니까요!) 

## PR point 답변
1. entryPoint보단 해당 VC에 맞는 형태로 이름을 바꾸면 어떨까 싶네요~!  PostDetail에서도 enum PostAuthor을, FirstCreateGroup에서도 enum PostMode와 같은게 있는 거 같습니다.
2. AuthManager에 하신건 좋으나, 아무래도 참여한 채팅방이 추가될때나 이럴때 감지를 못하는게 단점이 아닐까 싶습니다. 이걸 참여 채팅방, 닉네임변경, 참여 클럽등이 바뀔떄마다 다시 함수를 호출하는것보단 listener를 별도로 쓰는게 더욱 좋은 구현이 아닐까 싶네요!

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
>          view.delegate = self
p2;
위에 언급한대로 이것도 생성자대신 이러한 형태라면 가독성이나, 유지보수에 더 용이할 거 같습니다~!
```suggestion
let numberOfGroupPeopleView = NumberOfGroupPeopleView()
        if entryPoint == .revise, let maximum = club?.maxNumberOfPeople {
            groupCategoryView.selectAlreadyCategory(selectedCategory: maximum)
        }
        numberOfGroupPeopleView.delegate = self
        return numberOfGroupPeopleView
```

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +        self.club = club
p5;
해당 부분또한 함수로 전환한 뒤, 해당 함수가 호출됐을때 NumberOfGroupPeopleView, groupCategoryView 등에서 select category들만 호출되는 형태로 전환하고 싶은 마음이 있습니다. 하지만, 시간이 촉박한 관계상 다음 리팩토링때 함수형태로 전환하도록 하겠습니다~!

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
>          delegate?.didSelectedItem()
q;
cell은 사용하지 않는 변수인데, 어떠한 이유로 남아있는걸까요~?

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
> +        }
dataSource에서는, 해당 콜렉션뷰들의 데이터를 채우는 함수로서 그와 관련된 것들만 오는게 좋을거 같아요
불필요하게 if-else문을 통해서 체크해서 selectItem을 하는건 기능 저하등을 유발하는 요인이 될 거 같아요~!

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
> +    }
q;
어떤건 convenience init을 사용하고, 어떤건 super.init의 다른 형태를 사용했는데 기준이 있으실까요?

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
> +    }
위에서 제가 말한 initializing 방식이 아닌, 함수형태를 사용한다면 해당 생성자는 필요가 없을 것 같습니다~!

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
> +
selectedNumber를 별도로 저장하는 형태를 사용하지 않아도 가능합니다~!
```suggestion
func selectAlreadyNumberOfPeople(maximumNumber: Int) {
        guard let index = numberList.firstIndex(of: "\(maximumNumber)명") else { return }
        let indexPath = IndexPath(item: index, section: 0)
        numberCollectionView.selectItem(at: indexPath, animated: true, scrollPosition: .bottom)
    }
    
```

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
> +        }
```suggestion
```

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +
p1;
불필요한 개행은 지워주세요~!

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +
p1; 불필요한 개행은 지워주세요~!

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        }
p1;
이전 라인과 반복되는 설명이지만, 해당 datasource method는 cell의 데이터를 채워넣기 위한 함수입니다. 별도의 클릭을 위한 것들은 다른 함수에서 selectItem을 하는게 더 좋을거 같습니다~! 불필요하게 if-else문을 사용한다면 기능 저해를 유발합니다!(if-else는 생각보다 컴퓨터 구조적으로 큰 resource를 사용합니다.)
```suggestion
```

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        print(index)
불필요한 print를 발견했네여!! 삭제부탁드려요
```suggestion
```

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
>      func getSelectedCategory() -> String? {
p1;
get 발견~! 혹시 기회가 되시면 get을 삭제하고 selectedCategory로 해주세요.
```suggestion
    func selectedCategory() -> String? {
```

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +    }
밑에 NumberOfGroupPeopleView 처럼 구현할 시 생성자가 별도로 필요가 없어집니다~!
```suggestion
```

2022-11-27 12:24 UTC, yudonlee commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
p1;
이전에 반영한대로, 해당 View는 특정 변수에 따라서 두가지로 구분되거나 달라지는 형태가 아닌, 선택이 미리 되었냐 안되었냐의 차이기 때문에 특정 값이 존재한다면 그것만 select하는게 좋을거 같습니다~! 
```suggestion
func selectAlreadyCategory(selectedCategory: String) {
        guard let index = categoryList.firstIndex(of: selectedCategory) else { return }
        let indexPath = IndexPath(item: index, section: 0)
        categoryCollectionView.selectItem(at: indexPath, animated: true, scrollPosition: .bottom)
    }
```

2022-11-28 06:54 UTC, ccdkk commented on Vegeting/Screens/GroupList/Component/ClubListCollectionView.swift
> +        Task {
pull 받으니 outdated 되었군요!

2022-11-28 07:02 UTC, ccdkk commented on Vegeting/Screens/GroupList/Component/ClubListCollectionView.swift
> +            let detailViewController = PostDetailViewController(club: clubList[indexPath.item], entryPoint: isMine ? .mine : .other)
> p1;
selectedClub을 통해서 가독성을 높이고자 하신 것 같은데, 실제 함수 파라미터에는 clubList[indexPath.item]이 들어가있네요~!

didSelectedItem의 indexPath를 넣어 선택된 club을 할당해 준 것인데 네이밍이 어색하다는 걸까용?

> p3;
selectedClub으로 분리해두었다면, .mine과 .other도 분리하시면 더 좋을거 같아요~!

좋아요!

>p5;
저는 navigation시에, vc등 약어를 사용하는데 풀네임을 사용하는게 팀프로젝트시에는 더 좋아보이더라고요. 해당 destination을 잘못 설정했을 경우, 팀원이 찾아줄수도 있을거 같아서요! 그래서 저는 풀네임으로 하시는것도 건의드려봅니다~!

저도 주로 viewController를 사용하여 다른 곳에서는 모두 viewController라고 선언해줬던 것 같아요. 그래서 다시 보니 viewController로 바꾸고 싶어요. postDetailViewController라고 네이밍하면 뭔가 중복되는 느낌이 들고, viewController를 사용하는 부분
`tapDelegate?.clubListCellTapped(viewController: detailViewController)`이 바로 나오기 때문에 가독성도 떨어지지 않을 것 같은데 어떻게 생각하시나요? 사실 정답이 없는 부분이라 컨벤션으로 맞춰도 좋을 것 같아요

2022-11-28 12:06 UTC, ccdkk commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
>          }
너무 좋네요! 저도 작성하면서 너무 길다고 생각했었는데!! [5f2ea46](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/5f2ea463950cb53e7011b9f5830759788d359168)에서 반영하였습니다!

2022-11-28 12:12 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
>          delegate?.didSelectedItem()
이런..![e072b26](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/e072b262ab5edd4fa1dc92fa422a81f652d821b4)에서 삭제했습니다!

2022-11-28 12:13 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
좋아요. entryPoint에 따라 꼭 받아야할 필요가 없는 친구이기 때문에 init으로 받지 않고 함수로 넘겨주는 게 좋겠군요![8d95f61](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/8d95f613edbbde680f435a2a33b3d594df9ef022)에서 반영완료!

2022-11-28 12:14 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +    }
[8d95f61](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/8d95f613edbbde680f435a2a33b3d594df9ef022)반영 완료!

2022-11-28 12:15 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        }
if-else가 그런 무서무서운 친구였군요. [8d95f61](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/8d95f613edbbde680f435a2a33b3d594df9ef022)에서 반영하였습니다!
그런데 cell 에 selected 된 상태를 넘겨주는 것은 cellForItemAt에서 해줄 수 있는 내용이지 않나요?

2022-11-29 00:34 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +        }
[d79d363](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/d79d363ad5f37069b7a67132148874e10fefcc65)에서 반영 완료!

2022-11-29 00:35 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        print(index)
지운적이 없는데 해결되어 있네요! 반영 완료!

2022-11-29 00:39 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +            view = GroupCategoryView(selectedCategory: club?.clubCategory)
[8d95f61](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/8d95f613edbbde680f435a2a33b3d594df9ef022)에서 반영완료! 꼭 넘겨줘야할 데이터가 아니여서 함수로 빠지는게 좋은 것 같네요!!

2022-11-29 00:59 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
>          view.delegate = self
[ee60d72](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/ee60d72c8868fc88a065c29f3cd72b9c42ffb49e), [6498754](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/6498754041f6b0398a18aaf6bd0ec4278a1db033)에서 반영 완료

2022-11-29 01:05 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
> +        }
[ee60d72](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/ee60d72c8868fc88a065c29f3cd72b9c42ffb49e)에서 반영완료!

2022-11-29 01:05 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
> +    }
[ee60d72](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/ee60d72c8868fc88a065c29f3cd72b9c42ffb49e)에서 반영완료

2022-11-29 01:05 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
> +
[ee60d72](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/ee60d72c8868fc88a065c29f3cd72b9c42ffb49e)에서 반영 완료!

2022-11-29 01:08 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/Components/NumberOfGroupPeopleView.swift
> +        }
[4bd02c9](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/4bd02c9ab6e28473de3430e2878d4e6f085ec66f) 에서 반영완료!

2022-11-29 01:08 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +
[37a93a2](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/37a93a2e1515f52baf59a5d8405d7b183aa97bde) 반영완료!

2022-11-29 01:08 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +
[37a93a2](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/37a93a2e1515f52baf59a5d8405d7b183aa97bde) 반영완료!

2022-11-29 07:26 UTC, ccdkk commented on Vegeting/Global/Manager/AuthManager.swift
> +        }
동의합니다![b5c337b](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/b5c337bebbe92e350db9bf15e08c96d3ae427fd9)요렇게 해결해 봤습니다. 제대로 구현된게 맞을까요? firebase에서 user 정보를 수정하면 currentuser가 갈아껴지는 것은 확인했습니다.

2022-11-29 08:13 UTC, ccdkk commented on Vegeting/Global/Manager/AuthManager.swift
> +    }
[4db0989](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/4db0989090b7c0b2d22b11de22f744e83408cfae)에서 fetch로 수정해봤는데.. 썩 마음에 들지가 않네요 ㅜㅜ 좋은 네이밍이 있을까요?

2022-11-29 08:17 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
>      func getSelectedCategory() -> String? {
[3c74305](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/3c7430576252ae41d20941dc559a131c011a1428)에서 반영완료!

2022-11-29 08:17 UTC, ccdkk commented on Vegeting/Global/Manager/AuthManager.swift
> +    }
기존의 current 유저를 user로 수정하고 함수명을 currentUser로 수정해봤는데 어떤가요? [8fdab30](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/8fdab30b5b7124a72f25e5b4f77bd82f3bd6f115)

2022-11-29 08:18 UTC, yudonlee commented on Vegeting/Global/Manager/AuthManager.swift
> +    }
currentUser는 어떨까요~? swift에서는 get 네이밍을 굳이 붙이지 않아도 상관없을거 같아여~

2022-11-29 08:22 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +        }
when등을 명시하니 더욱 가독성이 좋은 것 같습니다~!
우리팀이 주석문화가 없었네요.. 주석문화를 만들어야 할 거 같습니다~!

2022-11-29 09:43 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +        }
오홍 어떤 주석문화를 말씀하시는 걸까요?

2022-11-29 23:48 UTC, yudonlee commented on Vegeting/Global/Manager/FirebaseManager.swift
> +            }
해당 함수는 throw함수가 아니라, catch문에서 어떤 결과를 나타내주지 못하는 상황입니다.
completion handler를 통해서 error를 리턴해주면 더욱 좋을 것 같습니다~!

2022-11-29 23:48 UTC, yudonlee commented on Vegeting/Global/Manager/AuthManager.swift
> +        }
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164#discussion_r1035393457 참고해주세여~!

2022-11-29 23:50 UTC, yudonlee commented on Vegeting/Screens/GroupList/Component/ClubListCollectionView.swift
> +            let detailViewController = PostDetailViewController(club: clubList[indexPath.item], entryPoint: isMine ? .mine : .other)
1. 첫번째 질문 
PostDetailVC의 생성자를 보면 clubList[indexPath.item]으로 되어있습니다.
하지만 selectedClub이 해당 값들을 이미 저장하고 있는 상황이라서 해당 변수를 활용하는건 어떤지에 대한 리뷰였습니다!

2022-11-30 00:02 UTC, yudonlee commented on Vegeting/Screens/GroupList/Component/ClubListCollectionView.swift
> +            let detailViewController = PostDetailViewController(club: clubList[indexPath.item], entryPoint: isMine ? .mine : .other)
2. viewController로 통일하자는 의견
그 부분은 아직 합의가 되지 않았던 거 같은데, 저는 리뷰하면서 해당 destination이 잘못됐을 때 실수를 바로 잡아줄수 있다고 생각해요 
예를 들면 원래 Destination을 ChatRoomViewController로 가야할 때 실수하는 상황입니다.
저는 오히려 약어 사용을 하지 않을거라면 더욱 분명하게 하는게 더 좋은거 같아서 팀원분들과 이야기를 나눠봅시다
```swift
let viewController = ChatRoomListViewController() 
```

```swift
let chatRoomViewController = ChatRoomListViewController() 
```

2022-11-30 01:01 UTC, ccdkk commented on Vegeting/Global/Manager/FirebaseManager.swift
> +            }
와 저기를 통으로 비워놓았네요.. [768d936](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/164/commits/768d9365eb62db434c8e55e4b428471657657b66)에서 반영하였습니다.

2022-11-30 01:04 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +        }
해당 함수에 대한 설명을 거의 본적이 없는거 같아서요. 파베쪽에서만 설명다는것도 불규칙적으로 달아논 거 같아서, 분명하게 무슨 함수인지 설명하는게 필요한 거 같아요

2022-11-30 01:09 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
>          view.delegate = self
p4;
두가지 모두 select와 관련된 함수명으로 바꿔주시면 더욱 좋을거 같습니다~~

2022-11-30 02:43 UTC, yudonlee approved these changes

2022-11-30 02:43 UTC, merged