Feature/162 second create view hi fi
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #165
Opened 2022-11-24 10:45 UTC by ccdkk

## 🌱 관련 이슈
- Close #162 

## 🌱 구현/변경 사항 및 이유
- SecondCreateView에 hi-fi를 적용하였습니다.
- textField, textView 수정시 UI 변경
- FirstCreateGroup에서 선택한 SecondCreateGroup에 연결합니다.
- textView를 editing할 때 키보드 때문에 textView가 가려지는 현상이 있어서 scrollView를 추가하여 `setContentOffset`메소드를 활용하여 높이를 조절해줍니다. 이때 조절하는 높이는 키보드의 높이에 맞추려고 했습니다. 키보드의 높이는 키보드가 실행될 때 전달되는 notification을 통해서 계산할 수 있습니다.
```Swift
 NotificationCenter.default.addObserver(self,
                                               selector: #selector(calculateKeyboardHeight),
                                               name: UIResponder.keyboardWillShowNotification,
                                               object: nil)
```
keyboard가 show되기 전에 selector를 실행시키고 
```Swift
 private func calculateKeyboardHeight(notification: NSNotification) {
        guard let keyboardSize = (notification.userInfo?[UIResponder.keyboardFrameEndUserInfoKey] as? NSValue)?.cgRectValue
            else { return }
        keyboardHeight = keyboardSize.height
    }
```
selector 함수에서 keyboard height를 계산하여 할당해줍니다. 이 때 할당되는 프로퍼티에 `private lazy var keyboardHeight: CGFloat = self.view.frame.height * 0.4` 이렇게 기본값으 줬는데요, 그 이유는 스크롤해주는 함수 `scrollVertical(to: keyboardHeight)`가 실행되는 시점인 `textViewDidBeginEditing`보다 `keyboardWillShowNotification` 시점이 더 느리기 때문에 textView를 최초로 클릭할 때는 키보드 height만큼 스크롤되지 않기 때문입니다. 그래서 iPhone13에서 키보드와 화면 비율을 계산하여 `view.height * 0.4`의 값을 주었습니다.

## 🌱 PR Point
- entryPoint라는 네이밍이 적절한가요?

## 🌱 참고 사항
![Simulator Screen Recording - iPhone 13 - 2022-11-24 at 19 44 29](https://user-images.githubusercontent.com/91456952/203764730-2b052c17-a49f-41c3-af9b-4b410b50fa1a.gif)

2022-12-03 06:18 UTC, yudonlee requested changes
Dake 수고하셨습니다!! TextView떄 ScrollView의 contentSize를 발견했던 동지로서 반가운 코드였습니다 😁

2022-12-03 06:18 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +    private lazy var keyboardHeight: CGFloat = self.view.frame.height * 0.4
q;
conversation에서는 사용하는걸로 되어있는데, 찾아봐도 해당 변수를 사용하는 지점이 없는데 혹시 어떤 의도가 있을까요~?

2022-12-03 06:18 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +//    }
p1;
주석 처리된 코드들은 지워주세요~!

2022-12-03 06:18 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +        let bottomOffset = CGPoint(x: 0, y: scrollView.contentSize.height - scrollView.bounds.size.height + scrollView.contentInset.bottom)
q; 
저희 scrollView에서는 scrollView에 contentInset을 주지 않았는데 어떠한 연유로 플러스 했는지 알고 싶습니다. 
디버깅시에도 값이 0으로 나옵니다!
<img width="423" alt="image" src="https://user-images.githubusercontent.com/39371835/205427435-554afabb-a68a-45d7-a3ef-9c1f26a94c3c.png">

2022-12-03 06:18 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +            scrollView.setContentOffset(bottomOffset, animated: true)
p3;
해당 offset의 의미는 bottomOffset이라기 보단, 현재 scrollView offset + 해당 offSet = ScrollView의 bottomOffset인 것 같습니다.
그래서 bottomOffset대신 scrollHeightOffset이라는 표현은 어떨까요? 또한 y를 계산한 식들을 따로 빼서 scrollHeight라는 점을 좀 더 부각하면 가독성이 더 좋을 것 같습니다. 

```suggestion
        let scrollHeight =  scrollView.contentSize.height - scrollView.bounds.size.height
        let scrollHeightOffset = CGPoint(x: 0, y: scrollHeight)
        if scrollHeight > 0 {
            scrollView.setContentOffset(bottomOffset, animated: true)
```

2022-12-03 06:18 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +    }
q;
해당 함수는 caller가 없는데 어떤 이유로 남아있는지 궁금합니다!!

2022-12-03 06:18 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +        // TODO: url로 넘기지 말고, UIimage로 넘겨서 image 변화여부를 체크하여 getImageURL을 호출해야할 것 같아요.
q;
주석 처리된 것들은 다음에 사용할 예정인가요?!

2022-12-03 06:18 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
>          }
p1;
해당 부분은 escaping closure가 실행되기 때문에 반드시 weak reference로 바꿔야 할 것 같습니다! 이제 확인했네요.

2022-12-04 02:49 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/Component/PhotoPickerView.swift
> +            self.setLabelText(title: "", sub: "")
[7b1a633](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/165/commits/7b1a633c11c5371887c2903d62311280fb961b49)에서 반영하였습니다!

2022-12-04 02:49 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/Component/PhotoPickerView.swift
>                      self.isDefaultImage = false
[7b1a633](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/165/commits/7b1a633c11c5371887c2903d62311280fb961b49)에서 반영하였습니다!

2022-12-04 02:52 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +    private lazy var keyboardHeight: CGFloat = self.view.frame.height * 0.4
처음에는 conversation에서 설명한 대로 사용했었는데, 그때 닐과 얘기하고난 후 버튼의 bottomConstraint를 keyboard Layout에 줌으로써 keyboard가 올라올 때 굳이 keyboard의 높이를 계산해서 scroll해줄 필요가 없더라구요! 그 내용을 conversation에 반영하지 못했네요 [a6479db](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/165/commits/a6479db538f1918688f79a17caa5d034f1b9491a)에서 해당 프로퍼티 삭제했습니다!

2022-12-04 02:53 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +        let bottomOffset = CGPoint(x: 0, y: scrollView.contentSize.height - scrollView.bounds.size.height + scrollView.contentInset.bottom)
뭔가 bottom inset이 추가되는 상황까지 고려해야하나 생각하다보니, 일어나지 않은 상황에 대해 과민 반응한 느낌이 있는 것 같긴 하네요! 
[501b373](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/165/commits/501b373ee36b318dc5a269416a4a96ac82788e80)에서 삭제하였습니다.

2022-12-04 02:54 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +            scrollView.setContentOffset(bottomOffset, animated: true)
[cae14c9](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/165/commits/cae14c954e2838b0d9c18422cd31197d73298263) 요렇게 반영해봤는데 어떨까요?

2022-12-04 02:54 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +    }
에고..keyboard layout으로 anchor를 바꾸면서 생긴 lagecy코드네요![8788497](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/165/commits/878849701961617c922fd630a1d530ffe64cecb2)에서 삭제했습니다!

2022-12-04 03:02 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +        let viewController = SecondCreateGroupViewController(club: club, incompleteClub: passedData, entryPoint: entryPoint)
일관성있게 바꾸는게 좋을 것 같아서 FirstCreateGroupVC에서도 해당 네이밍으로 변경했습니다!
[2e9fee1](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/165/commits/2e9fee1894ea2a3da116bea3da22d0c4c91963f9)에서 반영완료

2022-12-04 03:12 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
>          }
q
weak reference로 바꾸라는 것이 [weak self]를 사용하라는 것인가용? 프로퍼티 모두 함수 내에 있는 것들을 사용해서 self라는 키워드를 사용하지 않음에도 weak reference해주는 효과가 있나용?

2022-12-04 09:00 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +        // TODO: url로 넘기지 말고, UIimage로 넘겨서 image 변화여부를 체크하여 getImageURL을 호출해야할 것 같아요.
네 맞습니다 게시물 수정시 사용될 것 같아요

2022-12-04 09:00 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +//    }
[126e5df](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/165/commits/126e5dfd4d33e5d69ffcd3b9d9649d796d26a007)에서삭제했씁니다~

2022-12-04 10:54 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
> +            scrollView.setContentOffset(bottomOffset, animated: true)
아주 좋숩니당

2022-12-04 10:59 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/SecondCreateGroupViewController.swift
>          }
어?? 아니요! self를 호출하는 무엇인가가 있었던 거 같은데 잘못 봤나봐요

2022-12-04 11:00 UTC, yudonlee approved these changes

2022-12-04 13:21 UTC, merged