[FEAT] GroupCategoryCollectionView 구현
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #21
Opened 2022-10-22 14:26 UTC by ccdkk

## 🌱 관련 이슈
- #9 

## 🌱 구현/변경 사항 및 이유
- 모임 카테고리 collectionView를 구현하였습니다.
- 공용으로 사용될 수 있을 것 같아서 Global UIComponent에 만들었습니다.

## 🌱 PR Point
- 변수명이 적절한지 확인부탁드립니다!
- FirstCreateGroupViewController 에서는 아직 viewModel로 사용할만한 친구가 없는 것 같아서 사용하지 않았는데 혹시 사용하면 좋을 부분이 있다면 코멘트 부탁드립니다.
- GroupCategoryCollectionView와 같은 component를 만들 때에도 viewModel을 사용하는지, viewController에만 viewModel을 사용하는지 궁금합니다.
- 현재 layout은 se모델에서만 콜렉션뷰의 스크롤이 가능한데, 차라리 노치가 있는 모델과 없는 모델을 구분하여 노치가 있는 모델에 한해서는 collectionView의 layout을 `view.centerXAnchor`로 잡아줄까 고민중입니다. 의견 부탁드려요!

## 🌱 참고 사항
![Simulator Screen Recording - iPhone 13 - 2022-10-22 at 23 20 06](https://user-images.githubusercontent.com/91456952/197344464-c26707b0-d58e-491f-8ece-6f1f90afaee9.gif)

2022-10-23 01:08 UTC, wonhui-kim requested changes

2022-10-23 01:08 UTC, wonhui-kim commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +    }
p2;

똑같은 함수가 두 개가 있네요!

2022-10-23 01:09 UTC, wonhui-kim requested changes

2022-10-23 01:09 UTC, wonhui-kim commented on Vegeting/Global/UIComponent/Cell/GroupCategoryCollectionViewCell.swift
> +
p4;

의도하지 않은 공백이신 듯 하여 코멘트 남깁니다!

2022-10-23 01:13 UTC, wonhui-kim commented on Vegeting/Global/Extensions/UIView+Extension.swift
> +    @discardableResult
처음 접했는데, 해당 어노테이션을 사용하여 반환값이 사용되지 않는 데서 오는 warning 메시지를 제거할 수 있군요!

2022-10-23 05:13 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +    }
첫번째는 cell이 select 되었을 때 실행되는 내장함수이고 두번째는 선택된 cell이 deselect 되었을 때 실행되는 함수입니다! 
선택한 cell외에 다른 cell을 선택할 때 기존의 cell을 변경해주기 위에 두 개의 내장함수를 사용하였습니다.

2022-10-23 05:18 UTC, ccdkk commented on Vegeting/Global/Extensions/UIView+Extension.swift
> +    @discardableResult
맞습니다! 다음과 같이 discardableResult를 사용하지 않고도 표현하는 방법도 있다고 하네요!
```Swift
_ = saySomething() // discardableResult를 사용하지 않고 경고메시지 숨기기
```

2022-10-23 05:18 UTC, ccdkk commented on Vegeting/Global/UIComponent/Cell/GroupCategoryCollectionViewCell.swift
> +
[da505b9](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/21/commits/da505b9675325328c169baffb754a0d15d944bc0)에서 반영하였습니다!

2022-10-23 06:36 UTC, yudonlee reviewed
고생하셨습니다. 의견 참고해서 달아주시면 될 것 같습니다.

2022-10-23 06:36 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +                                          padding: UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0))
autolayout을 extension으로 추가하셔서 쓰시고 계시네요! 저는 이렇게 쓰다가 원래대로 사용하고 있습니다.
각자만의 스타일이 다른 것 같아서 이건 개인의 취향으로 사용해야 겠네요

2022-10-23 06:36 UTC, yudonlee commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +    }
저는 하나의 캐러셀이 반드시 선택되어 있는다고 생각했는데, 모두 해제되는 경우에 전체를 보여주는 형식이네요

2022-10-23 06:36 UTC, yudonlee commented on Vegeting/Global/UIComponent/Cell/GroupCategoryCollectionViewCell.swift
> +        configureUI()
configureUI말고 다른 표현은 어떤가요? configure는 데이터를 전달하는 의미로 쓰이고 싶습니다. 
```swift
setupComponent
setupUI
```
등으로 바꾸고 싶어요

2022-10-23 06:36 UTC, yudonlee commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        categoryCollectionView.register(GroupCategoryCollectionViewCell.self, forCellWithReuseIdentifier: GroupCategoryCollectionViewCell.className)
p2;
해당 register부분은 collecitonView의 선언부 클로저 안으로 넣어도 될 것 같습니다.
```swift
    private let categoryCollectionView: UICollectionView = {
        collectionView.register(GroupCategoryCollectionViewCell.self, forCellWithReuseIdentifier: GroupCategoryCollectionViewCell.className)
    }
```

2022-10-23 06:36 UTC, yudonlee commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        cell.setItemLabel(with: categoryList[indexPath.item])
p3;
저는 cell을 구성하는 데이터를 넘겨줄 때 
```swift
configure(with data: model) {
}
```
로 사용하는 편입니다. cell list에서 특정 VC로 이동할 때, 데이터를 넘겨줄때도 동일한 함수명을 사용합니다. setItemLabel은 해당 label하나만을 가르키는 느낌이라, 해당 셀의 전체 값을 구성하는 데이터를 넘겨주는 느낌으로 바꾸는 건 어떤가요? 
월요일 날 모두 모여 이야기하고 싶습니다.

2022-10-23 06:36 UTC, yudonlee commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: GroupCategoryCollectionViewCell.className, for: indexPath) as? GroupCategoryCollectionViewCell else { return UICollect
p1;
indent 오류입니다. 
```swift
return UICollectionviewCell() }
```

2022-10-23 06:36 UTC, yudonlee commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        return CGSize(width: width, height: 34)
q;
width를 산정한 이유가 있을까요? 궁금합니다~

2022-10-23 06:36 UTC, yudonlee commented on Vegeting/Global/UIComponent/Cell/GroupCategoryCollectionViewCell.swift
> +        itemLabel.font = isSelected ? .preferredFont(forTextStyle: .subheadline, compatibleWith: .init(legibilityWeight: .bold)) : .preferredFont(forTextStyle:.subheadline)
삼항연산자를 쓰셔서 잘 해결한 것 같습니다.
하지만  Delegate내부에서 함수를 호출하지 않고, Cell에 내장된 isSelected를 did set을 통해서도 해결 가능합니다!
참고하시면 좋을 것 같습니다.
```swift
override var isSelected: Bool {
        didSet {
            if isSelected {
                contentView.backgroundColor = .mainBlue
            } else {
                contentView.backgroundColor = .mainGray
            }
        }
    }
```

2022-10-23 06:49 UTC, wonhui-kim commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +    }
아하! 자세히 보니 didSelectItemAt / didDeselectItemAt 이 부분이 다르네요 😂
저렇게 같이 쓰기도 하는군요!

2022-10-23 09:08 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +    }()
<img width="192" alt="스크린샷 2022-10-23 오후 6 08 01" src="https://user-images.githubusercontent.com/91456952/197383892-e4ccfe07-cc1c-4845-a130-a9f908a5b50c.png">
넵 title역할을 하는 Label로 항상 보여야 하는 뷰입니다! 그래서 private let으로 선언하였습니다.

2022-10-23 09:14 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +    }
@yudonlee 모두 해제되는 경우에 전체를 보여주는 형식이란게 어떤 의미인가요?🧐

2022-10-23 09:17 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: GroupCategoryCollectionViewCell.className, for: indexPath) as? GroupCategoryCollectionViewCell else { return UICollect
[51938ac](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/21/commits/51938ac7e5d1cb0e2b34505f670aa65cb26da9bf)에서 반영하였습니다.

2022-10-23 09:21 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        return CGSize(width: width, height: 34)
현재는 모두 두 글자여서 상관없지만 추후에 글자수가 다른 카테고리가 들어올 수 있다고 생각하여 글자수에 대응한 width를 주려고 하였습니다.

2022-10-23 09:22 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +        return label
[6f4bbf1](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/21/commits/6f4bbf1eb8ce995669c586e05975f6c62e867425)에서 반영하였습니다.

2022-10-23 09:37 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        cell.setItemLabel(with: categoryList[indexPath.item])
저는 보통 `setupData(with data: model) { }` 을 사용합니다. label의 text만을 바꿔주는 코드라 `setupData`라고 거창하게 명명하는것은 오히려 함수명만 봤을 때 추상적으로 다가올 수 있다고 생각합니다. 
그렇지만 MVVM 패턴에서는 저렇게 명명하는 것도 좋아보이네요! 뭔가 configure이라는 동사를 여러 함수의 prefix로 사용하다보니, configure 단독으로 사용되는 것은 팀 내부에서는 괜찮겠지만 외부인이 코드를 볼 때 가독성 측면에서 떨어질 수 있다고 생각합니다. 월요일 날 얘기해보면 좋을 주제인 것 같아요 ! 공용으로 사용되는 함수명 다 얘기해봐요 :)

2022-10-23 09:42 UTC, ccdkk commented on Vegeting/Global/UIComponent/Cell/GroupCategoryCollectionViewCell.swift
> +        itemLabel.font = isSelected ? .preferredFont(forTextStyle: .subheadline, compatibleWith: .init(legibilityWeight: .bold)) : .preferredFont(forTextStyle:.subheadline)
오 이렇게 override해서 사용하기도 하는 군요! 
isSelected에 따라 뷰에 많은 부분이 달라진다면 함수화 하여 알려주신 접근법과 유용하게 사용할 수 있을 것 같습니다. 감사해요!

2022-10-23 09:57 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +        view.addSubview(categoryCollectionView)
오 이렇게 추가해줄 수도 있군요! 자주 쓰일 것 같은데 extension으로 빼는 것은 어떤가요?
```Swift

    func addSubviews (_ views: UIView...) {
        views.forEach { [weak self] view in
            self?.addSubview(view)
        }
    }
```
`view.addSubViews(categoryCollectionView, categoryTitleLabel)`으로 사용될 것 같습니다.

2022-10-24 09:44 UTC, kelly1422 reviewed
수고하셨습니다!

2022-10-24 09:44 UTC, kelly1422 commented on Vegeting/Global/UIComponent/Cell/GroupCategoryCollectionViewCell.swift
> +        itemLabel.font = isSelected ? .preferredFont(forTextStyle: .subheadline, compatibleWith: .init(legibilityWeight: .bold)) : .preferredFont(forTextStyle:.subheadline)
q;
itemLabel.font = isSelected ? .preferredFont(forTextStyle: .subheadline, compatibleWith: .init(legibilityWeight: .bold)) : .preferredFont(forTextStyle:.subheadline)
이 부분은 선택된 셀의 폰트스타일을 볼드로 하기 위함인가요?? 차이가 없는거 같아 질문 드립니다~

2022-10-24 09:44 UTC, kelly1422 commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +    private let categoryList: [String] = ["행사", "맛집", "친목", "공부", "기타"]
나중에 그룹 리스트를 보여줄때도 재사용하려면 전체도 있어야될거 같아서 나중에 categoryList는 값을 전달받는 식으로 하면 되지 않을까 한번 생각해봤습니다~

2022-10-24 09:50 UTC, ccdkk commented on Vegeting/Global/Extensions/UIView+Extension.swift
> +    func makeShadow(color: UIColor,
UIView Extension으로 원래 넣으려고 했는데 이제 추가하게 되었습니다!

2022-10-24 09:53 UTC, ccdkk commented
@kelly1422  넵 맞습니다 bold를 적용하기 위함입니다.

2022-10-24 09:55 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +        view.addSubview(categoryCollectionView)
좋습니다! MC3에서도 해당 Extension을 추가했었습니다.

2022-10-24 10:04 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +    private let categoryList: [String] = ["행사", "맛집", "친목", "공부", "기타"]
동의합니다! [8576428](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/21/commits/857642854cb1ca82ccf68f3204a0a8308d5ca755)에서 categoryList를 변경하는 함수를 추가해봤습니다.

2022-10-24 10:08 UTC, kelly1422 commented on Vegeting/Global/Extensions/UIView+Extension.swift
> +    func makeShadow(color: UIColor,
나중에 사용될 예정이라 미리 넣어놓으신건가요?!

2022-10-24 12:13 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        categoryCollectionView.register(GroupCategoryCollectionViewCell.self, forCellWithReuseIdentifier: GroupCategoryCollectionViewCell.className)
[3a866e8](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/21/commits/3a866e8b05c496bd7ba5684a1887c22fc0c32ff0)에서 반영했습니다.

2022-10-24 12:17 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/FirstCreateGroupViewController.swift
> +        view.addSubview(categoryCollectionView)
[4bd993c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/21/commits/4bd993cd837c69fea8c5e600efb913ffa9122d79)에서 추가하였습니다.

2022-10-24 12:17 UTC, ccdkk commented on Vegeting/Global/UIComponent/Cell/GroupCategoryCollectionViewCell.swift
> +        itemLabel.font = isSelected ? .preferredFont(forTextStyle: .subheadline, compatibleWith: .init(legibilityWeight: .bold)) : .preferredFont(forTextStyle:.subheadline)
넵 맞습니다 bold를 적용하기 위함입니다.

2022-10-24 12:17 UTC, ccdkk commented on Vegeting/Global/Extensions/UIView+Extension.swift
> +    func makeShadow(color: UIColor,
view 그림자 들어가는 경우가 많아서 미리 넣어놨습니다 ! 당장은 필요 없으니 삭제할까용?🧐

2022-10-25 01:20 UTC, kelly1422 commented on Vegeting/Global/Extensions/UIView+Extension.swift
> +    func makeShadow(color: UIColor,
쓸 일이 있을거 같으니 일단 냅둬도 좋을것 같아요!!

2022-10-25 01:23 UTC, wonhui-kim approved these changes

2022-10-25 01:24 UTC, kelly1422 commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +    private let categoryList: [String] = ["행사", "맛집", "친목", "공부", "기타"]
만약 여러 종류의 캐러셀이 있으면 디폴트 값이 정해져있는게 어떻게 보면 가독성을 해칠 수 있을거라는 생각에 아예 빈 배열로 두고 그때 그때 초기화 해주는 것도 좋을 것 같지만!! 
현재는 캐러셀을 보여주는 부분이 이 두부분 밖에 없는 거 같아 좋은것 같습니다!

2022-10-25 01:26 UTC, ccdkk commented on Vegeting/Global/UIComponent/GroupCategoryView.swift
> +        cell.setItemLabel(with: categoryList[indexPath.item])
[f3d972e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/21/commits/f3d972e050724380c8d8edadbfe948d8e56c4e81)에서 configure로 반영하였습니다.

2022-10-25 02:05 UTC, yudonlee approved these changes
고생하셨어요!

2022-10-25 02:06 UTC, merged