Feature/23 server model
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #26
Opened 2022-10-23 10:31 UTC by yudonlee

## 🌱 관련 이슈
- close #23 

## 🌱 구현/변경 사항 및 이유
1. 구조에 대한 부분은 #25 참고
2. property wrapper 
```swift
@DocumentID var id: String?
```
해당 부분은 서버에서 Document를 불러올 때 자연스럽게 DocumentID가 채워지게 됩니다. (Firebase의 property wrapper)

## 🌱 PR Point
이해할 수 있는 변수명인지 집중해서 봐주세요!

2022-10-23 10:53 UTC, wonhui-kim requested changes
수고 많으셨습니다! 
각 struct에 들어가는 이미지가 어떤 이미지인지 알 수 있는 네이밍이라면 더 좋을 것 같아요!

2022-10-23 10:53 UTC, wonhui-kim commented on Vegeting/Global/Models/Chat.swift
> +    let senderImageURL: String?
p5;

해당 변수가 프로필 사진을 의미하는 거라면 조금 직관적으로 senderProfileImageURL 로 설정하는 것은 어떨까요?

2022-10-23 10:53 UTC, wonhui-kim commented on Vegeting/Global/Models/Club.swift
> +    let clubID, clubTitle, clubCharacter, hostID: String
p5;

clubCharacter보다 clubCategory로 변경한다면 더 이해하기 쉬울 것 같습니다 🙂

2022-10-23 10:53 UTC, wonhui-kim commented on Vegeting/Global/Models/Participant.swift
> +    var imageURL: String?
p5;

여기도 해당 이미지가 프로필 사진을 의미한다면 profileImageURL로 변경하면 좋을 것 같습니다!

2022-10-23 10:53 UTC, wonhui-kim commented on Vegeting/Global/Models/Club.swift
> +    var imageURL: String?
p5;

어떤 이미지인지 알 수 있게 coverImageURL로 변경하면 어떨까요?!

2022-10-24 09:49 UTC, ccdkk commented on Vegeting/Global/Models/Chat.swift
> +import FirebaseFirestoreSwift
p1;
import 컨벤션에 따라 1st party와 3rd party 사이에 개행 추가해주세요!

2022-10-24 09:49 UTC, ccdkk commented on Vegeting/Global/Models/Chat.swift
> +    let participants: [Participant]?
q;
User의 형태로 넣지않고 Participant를 따로 만들어준 이유가 궁금합니다.

2022-10-24 09:49 UTC, ccdkk commented on Vegeting/Global/Models/Club.swift
> +import FirebaseFirestoreSwift
q1;
컨벤션 반영 부탁드려요!

2022-10-24 09:49 UTC, ccdkk commented on Vegeting/Global/Models/User.swift
> +    let chatID, chatName: String
q;
chatID와 id를 구분해서 사용하는 이유가 있나요?

2022-10-24 10:03 UTC, kelly1422 reviewed
수고 많으셨습니다~!!

2022-10-25 07:08 UTC, yudonlee commented on Vegeting/Global/Models/Chat.swift
> +    let contentType: String
네 맞습니다!

2022-10-25 07:08 UTC, yudonlee commented on Vegeting/Global/Models/Chat.swift
> +    let participants: [Participant]?
서버 모델링을 보시면 알겠지만, Chatting에 유저정보를 모두 가지고 있을 필요가 없기 때문입니다.

2022-10-25 07:08 UTC, yudonlee commented on Vegeting/Global/Models/Chat.swift
> +    let senderImageURL: String?
- https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/26/files#diff-88d3213a326e8c368ace580580c43155542b9dd39bab401b3b8e8c57a608685cR10-R14 반영되었습니다.

2022-10-25 07:09 UTC, yudonlee commented on Vegeting/Global/Models/Club.swift
> +    let clubID, clubTitle, clubCharacter, hostID: String
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/26/files#diff-830d4ecd7cb6eea9434ac8e2080e62dff26403694a22810d1ccaea70238e9c84R12-R20 반영되었습니다.

2022-10-25 07:10 UTC, yudonlee commented on Vegeting/Global/Models/Participant.swift
> +    var imageURL: String?
[해당부분](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/26/files#diff-88d3213a326e8c368ace580580c43155542b9dd39bab401b3b8e8c57a608685cR10-R13) 반영되었습니다.

2022-10-25 07:10 UTC, yudonlee commented on Vegeting/Global/Models/Club.swift
> +    var imageURL: String?
[해당부분](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/26/files#diff-830d4ecd7cb6eea9434ac8e2080e62dff26403694a22810d1ccaea70238e9c84R13-R18) 반영되었습니다

2022-10-25 07:10 UTC, yudonlee commented on Vegeting/Global/Models/Chat.swift
> +import FirebaseFirestoreSwift
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/26/files#diff-02844ced809dced58a5d8144651cd21c35436f2bef846cdc9b47689b5eba8f92R8-R11 반영되었습니다.

2022-10-25 07:11 UTC, yudonlee commented on Vegeting/Global/Models/Club.swift
> +import FirebaseFirestoreSwift
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/26/files#diff-02844ced809dced58a5d8144651cd21c35436f2bef846cdc9b47689b5eba8f92R8-R11 반영되었습니다.

2022-10-25 07:12 UTC, yudonlee commented on Vegeting/Global/Models/User.swift
> +    let chatID, chatName: String
Identifiable protocol을 따르면서, chatID라는 분명한 변수명을 사용하고 싶어서 두개를 별도로 사용했습니다. 후에 identifiable을 따르는 구조로 필요시 수정해도 문제는 없을 것 같습니다.

2022-10-25 07:12 UTC, yudonlee commented on Vegeting/Global/Models/Chat.swift
> +}
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/26/files#diff-50a0ac54233c8bc5584d566f84e0fed8ad94b64a1032633ac681a541d8c3d7c3R12-R15 반영되었습니당.

2022-10-25 07:13 UTC, yudonlee commented on Vegeting/Global/Models/Participant.swift
> +}
id는 identifiable protocol을 따르기 위한 용도고 uid는 유저의 개인 고유ID라는 것을 명확하기 위해서 만들어두었습니다.

2022-10-25 07:13 UTC, yudonlee commented on Vegeting/Global/Models/User.swift
> +    let participatedClubs: [ParticipatedClub]?
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/26/files#diff-02844ced809dced58a5d8144651cd21c35436f2bef846cdc9b47689b5eba8f92R12-R18 반영되었습니다.

2022-10-25 07:15 UTC, wonhui-kim approved these changes
수고하셨습니다 😁

2022-10-26 08:40 UTC, merged