[FEAT]: PostDetailView 내부 action sheet를 생성하였습니다.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #33
Opened 2022-10-24 13:56 UTC by wonhui-kim

## 🌱 관련 이슈
- #32 

## 🌱 구현/변경 사항 및 이유
게시글 수정, 삭제가 가능한 action sheet를 생성하였습니다. 
추후 TODO: 에 각 액션을 연결하면 됩니다.

## 🌱 PR Point

## 🌱 참고 사항
<img src="https://user-images.githubusercontent.com/96123303/197542711-dcd054ca-ac77-4f2c-8329-55a8cc51f4c6.png" width=200>

2022-10-25 01:51 UTC, ccdkk commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +class PostDetailViewController: UIViewController {
p2;
final 키워드 붙여주세요! 메모리 측면에서 좋아진다고 합니다.

2022-10-25 01:51 UTC, ccdkk commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +    private lazy var coverImageView: UIImageView = {
q;
필수로 생성되어야하는 친구들에게도 lazy를 선언해주신 이유가 있나요?

2022-10-25 01:51 UTC, ccdkk commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        return label
p2;
다른 멤버들과의 통일성을 위해 개행을 삭제하는 것은 어떤가요?

2022-10-25 01:51 UTC, ccdkk commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +//        stackView.backgroundColor = .blue
p1;
쓰지않는 주석이라면 삭제해주세요!

2022-10-25 01:51 UTC, ccdkk commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +//        label.backgroundColor = .purple
p1;
쓰지않는 주석이라면 삭제해주세요!

2022-10-25 01:51 UTC, ccdkk commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        view.backgroundColor = .white
p2;
다른 함수 `setupLayout(), setupNavBar()`의 함수들과 위계가 맞지 않는 것 같습니다. configureUI라는 함수안에서 설정해주는 것은 어떤가요?

2022-10-25 01:51 UTC, ccdkk commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        navigationItem.rightBarButtonItem = UIBarButtonItem(image: UIImage(systemName: "ellipsis"), style: .done, target: self, action: #selector(showActionSheet))
p2;
길어지는 함수의 경우 쉼표 다음에 enter를 넣어 가독성을 높이는 게 좋아 보입니다!
```suggestion
navigationItem.rightBarButtonItem = UIBarButtonItem(image: UIImage(systemName: "ellipsis"),
                                                    style: .done,
                                                    target: self,
                                                    action: #selector(showActionSheet))
```

2022-10-25 01:51 UTC, ccdkk commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +//            $0.heightAnchor.constraint(equalTo: $0.widthAnchor, multiplier: 1.0).isActive = true
p1;
주석삭제 부탁드립니다!
p5;
uistackView+Extension에 해당 고차함수와 같은 기능을 하는 extension이 있는데 활용해 보시는 것도 좋을 것 같습니다!

2022-10-25 01:51 UTC, ccdkk commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        let cancel = UIAlertAction(title: "취소", style: .cancel) { action in
p3;
deletePost은 alert임을 명시적으로 알려주는 네이밍은 아니라고 생각합니다.
titleLabel 이라고 네이밍을 하듯이 deletePostAlert라고 네이밍을 하는 것은 어떤가요? modifyPost, cancel도 같은 맥락입니다!

2022-10-26 05:41 UTC, yudonlee requested changes

2022-10-26 05:41 UTC, yudonlee commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +class PostDetailViewController: UIViewController {
저또한 상속이 필요하지 않다면 final을 추천드립니다.

2022-10-26 05:41 UTC, yudonlee commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        navigationItem.rightBarButtonItem = UIBarButtonItem(image: UIImage(systemName: "ellipsis"), style: .done, target: self, action: #selector(showActionSheet))
p2;
저는 파라미터 하나씩 끊는게 오히려 보기가 불편한데, 얘기 나눠볼까요?

2022-10-26 05:41 UTC, yudonlee commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +            titleLabel.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 20)
p2;
subView는 subView끼리 layout지정은 다른 함수에서 하길 권장드립니다. 
함수 하나에 모든 걸 담으려다 보니 보기가 어려운 것 같아요~

2022-10-26 05:41 UTC, yudonlee commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        }
p4;
```swift
let deleteAlertAction = ...
```
네이밍을 추천드립니다.

2022-10-26 05:53 UTC, yudonlee requested changes

2022-10-26 05:53 UTC, yudonlee commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +//            $0.heightAnchor.constraint(equalTo: $0.widthAnchor, multiplier: 1.0).isActive = true
p1;
map의 사용용도는 
___"Returns an array containing the results of mapping the given closure over the sequence’s elements."___ 입니다.
stack뷰에 뷰를 쌓는 요도로 사용하실 거면 forEach등 다른 고차함수를 쓰시는 건 어떨까요!?

2022-10-26 11:58 UTC, wonhui-kim commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +class PostDetailViewController: UIViewController {
[커밋](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/51/files#diff-d66f54c34c522784d11e53497bd8f83e47edf3fb460c3e3b39ea7ee798cf50b6R53) 반영하였습니다!

2022-10-26 11:59 UTC, wonhui-kim commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        return label
[커밋](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/51/files#diff-d66f54c34c522784d11e53497bd8f83e47edf3fb460c3e3b39ea7ee798cf50b6R74-R80) 반영하였습니다~

2022-10-26 12:00 UTC, wonhui-kim commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        view.backgroundColor = .white
[커밋](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/51/files#diff-d66f54c34c522784d11e53497bd8f83e47edf3fb460c3e3b39ea7ee798cf50b6R160-R162) 반영하였습니다!

2022-10-26 12:01 UTC, wonhui-kim commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +            titleLabel.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 20)
[커밋](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/51/files#diff-d66f54c34c522784d11e53497bd8f83e47edf3fb460c3e3b39ea7ee798cf50b6R171-R176) 반영하였습니다!

2022-10-26 12:07 UTC, wonhui-kim commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        let cancel = UIAlertAction(title: "취소", style: .cancel) { action in
[커밋](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/33/files#diff-a9086d0b3aa886d2557c5ac4818df9462c45fb638b60a6701d1ec5d298824062R128-R138) 반영하였습니다!

2022-10-26 12:07 UTC, wonhui-kim commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +        }
[커밋](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/33/files#diff-a9086d0b3aa886d2557c5ac4818df9462c45fb638b60a6701d1ec5d298824062R128-R138) 반영하였습니다~

2022-10-26 12:08 UTC, wonhui-kim commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +//            $0.heightAnchor.constraint(equalTo: $0.widthAnchor, multiplier: 1.0).isActive = true
그렇군요! 추후 코드 수정으로 stackView를 사용하지 않게 되어 해당 코드는 삭제했습니다!
map 대신 forEach를 쓰는 방법이 좋겠네요 😀

2022-10-26 12:09 UTC, wonhui-kim commented on Vegeting/Screens/PostDetail/PostDetailViewController.swift
> +class PostDetailViewController: UIViewController {
[커밋](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/51/files#diff-d66f54c34c522784d11e53497bd8f83e47edf3fb460c3e3b39ea7ee798cf50b6R53) 반영하였습니다 🙂

2022-10-26 15:19 UTC, yudonlee approved these changes

2022-10-26 15:29 UTC, ccdkk approved these changes
고생하셨습니다!

2022-10-26 15:31 UTC, merged