[FEAT]: searchController를 활용하여 지역검색 뷰를 구현하였습니다.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #52
Opened 2022-10-26 11:40 UTC by ccdkk

## 🌱 관련 이슈
- Close #28 

## 🌱 구현/변경 사항 및 이유
- SearchController를 활용하여 뷰를 구성하였습니다.
- kakao 장소검색 API, kakao 주소검색 API를 활용하여 검색 기능을 구현하였습니다.
- key값을 따로 저장하기 위해 현재는 key값을 빼놓은 상태라 
[카카오 디벨로퍼 참고 사이트](https://developers.kakao.com/docs/latest/ko/local/dev-guide)

## 🌱 PR Point
- 현재 페이징 기능을 구현하지 않고, 주소는 3개, 장소는 10개를 불러오도록 설정하였습니다.
- Alamofire까지는 아니여도 추후에 swift 기본 제공하는 JSON 다루는 함수들을 이용하여 swiftyJSON을 대체하고자 합니다.

## 🌱 참고 사항
![Simulator Screen Recording - iPhone 13 - 2022-10-26 at 20 38 51](https://user-images.githubusercontent.com/91456952/198016780-9d5603be-49e6-4f9a-ae6b-060af1d4fa1e.gif)

2022-10-26 15:56 UTC, yudonlee requested changes
반영해주세여!

2022-10-26 15:56 UTC, yudonlee commented on Vegeting/Global/Supports/SceneDelegate.swift
> +            let navigation = UINavigationController(rootViewController: FirstCreateGroupViewController())
p1;
SceneDelegate는 수정해주세요!

2022-10-26 15:56 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +    }
p3;
UI 관련 변경은 DispatchQueue.main에서 해주세요! warning이 뜨지 않았나요?

2022-10-26 15:56 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +    }
p3;
UI 관련 변경은 DispatchQueue.main에서 해주세요! warning이 뜨지 않았나요?

2022-10-26 15:56 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +                self.resultTableView.reloadData()
p2;
UI reload관련 함수는 main Queue에서 진행하셔야 합니다!

2022-10-26 16:06 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +    }
좋은 뽀인트군요! ARC검색해보겠습니다.[145826d](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/52/commits/145826ddde44d7c760ae97c474fc43d0ab76a539)에서 반영하였습니다!

2022-10-26 16:07 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +                self.resultTableView.reloadData()
[19386dd](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/52/commits/19386dded4472e1fe4207af7ab2bea724e434e1f)에서 반영하였습니다.

2022-10-31 18:06 UTC, kelly1422 reviewed
수고하셨습니다~!!

2022-10-31 18:06 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +import Alamofire
q;
이것들은 써드파티 아닌가요??

2022-10-31 18:06 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +    private func touchUpAddButton() {
p2;
back버튼을 눌렀을떄 실행되는 메소드인데 함수명이 직관적이지 않은것 같습니다!

2022-10-31 18:06 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +        AF.request(StringLiteral.kakaoRestAPIKeyword,
q;
오호.. 이 AF 가 Alamofire인가보군요

2022-11-01 12:11 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/Cells/SearchedAddressTableViewCell.swift
> +    let locationLabel: UILabel = {
[c065c7d](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/52/commits/c065c7d79245698e4e2986a66b22294e6b607259)에서 반영하였습니다!

2022-11-01 12:11 UTC, ccdkk commented on Vegeting/Global/UIComponent/Models/Address.swift
> +}
엇 이런.. [4a7312d](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/52/commits/4a7312ddaa1f8679e4f9598dd4112793f5057204)에서 반영하였습니다. 기존의 Models 폴더로 옮겼습니다.

2022-11-01 12:12 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +import Alamofire
맞습니다..! [a8cedf9](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/52/commits/a8cedf91055803450afaf7f32e7412c289cd2dea)에서 개행 추가 하였습니다.

2022-11-01 12:14 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +    private func touchUpAddButton() {
동의합니다. touchUpToPop이라는 네이밍은 어떤가요?

2022-11-01 12:14 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +        AF.request(StringLiteral.kakaoRestAPIKeyword,
넵 맞습니다!

2022-11-01 12:42 UTC, wonhui-kim commented on Vegeting/Global/Supports/SceneDelegate.swift
> +        window.rootViewController = UINavigationController(rootViewController: FirstCreateGroupViewController())
p1;

rootViewController는 ViewController로 원상복구 부탁드립니다!

2022-11-01 12:42 UTC, wonhui-kim commented on Vegeting/Screens/CreateGroup/Cells/SearchedAddressTableViewCell.swift
> +
p3;

개행 삭제해주세요~

2022-11-01 17:07 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +    private func touchUpAddButton() {
좋습니다!! 수정 부탁드려요~!

2022-11-02 01:09 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +    private func touchUpAddButton() {
[5d059ea](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/52/commits/5d059ea2f35d1d2435a5123a6c2d39c4430153e5)에서 반영하였습니다!

2022-11-02 01:09 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/Cells/SearchedAddressTableViewCell.swift
> +
[5446f19](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/52/commits/5446f190d059f2d00971c68c107e81a3691f517d)에서 반영하였습니다!

2022-11-02 01:09 UTC, ccdkk commented on Vegeting/Global/Supports/SceneDelegate.swift
> +        window.rootViewController = UINavigationController(rootViewController: FirstCreateGroupViewController())
[5446f19](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/52/commits/5446f190d059f2d00971c68c107e81a3691f517d)에서 반영하였습니다!

2022-11-02 01:10 UTC, wonhui-kim approved these changes
수고하셨습니다 🙂

2022-11-02 02:12 UTC, kelly1422 approved these changes

2022-11-02 02:38 UTC, yudonlee approved these changes

2022-11-02 07:57 UTC, merged