[FEAT]: 모집중인 클럽을 보여주는 collectionView
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #56
Opened 2022-10-26 15:13 UTC by kelly1422

## 🌱 관련 이슈
#49 

## 🌱 구현/변경 사항 및 이유
일단 테플을 위해 후다닥 해보았습니다

## 🌱 PR Point

## 🌱 참고 사항
![Simulator Screen Recording - iPhone 14 Pro - 2022-10-27 at 00 09 29](https://user-images.githubusercontent.com/80809782/198064824-4ebc0a57-c47d-4cf0-9abf-2314b5bc502a.gif)

2022-10-26 16:27 UTC, ccdkk commented on Vegeting/Screens/GroupList/Component/ClubListCell.swift
> +class ClubListCell: UICollectionViewCell {
p2;
final 붙여주세요! ClubListCollectionViewCell 이라고 명명하여 어떤 cell인지 명시해주는 것은 어떤가요?

2022-10-26 16:27 UTC, ccdkk commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +            collectionView.reloadData()
p3;
UI관련된 작업은 main queue에서 해주세요!

2022-10-26 16:27 UTC, ccdkk commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +        cell.layer.backgroundColor = UIColor.init(hex: "#e3e3e3").cgColor
q;
cgColor를 해주는 이유는 뭔가요?

2022-10-27 03:47 UTC, kelly1422 commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +        cell.layer.backgroundColor = UIColor.init(hex: "#e3e3e3").cgColor
layer의 백그라운드컬러는 cgColor 타입 입니다!

2022-10-27 03:48 UTC, kelly1422 commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +            collectionView.reloadData()
콜렉션뷰에 나타날 클럽리스트 배열의 변경이 있으면 relaod해줘야 한다고 판단해 위와 같이 작성하였는데,
혹시 어떻게 작성하라는 건가요??

2022-10-27 09:07 UTC, kelly1422 commented on Vegeting/Screens/GroupList/Component/ClubListCell.swift
> +class ClubListCell: UICollectionViewCell {
[d052317](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/56/commits/d0523179bf2e9d34035a2845bdb5e8c2516e75b4)
반영완료!

2022-10-27 10:27 UTC, ccdkk commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +        cell.layer.backgroundColor = UIColor.init(hex: "#e3e3e3").cgColor
오 그렇군요. 감사합니다~

2022-10-27 10:32 UTC, ccdkk commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +            collectionView.reloadData()
콜렉션 뷰를 reload 함으로써 UI의 변경이 생기므로 해당 함수는 UI와 관련된 작업입니다. UI관련된 작업을 main queue에서 해야하는 이유는 UIKit이 thread-safe 하지 않기 때문입니다! 
```suggestion
Dispatchqueue.main.async { 
            collectionView.reloadData()
}
```
관련 [블로그](https://jeong9216.tistory.com/515)를 첨부합니다!

2022-10-31 00:35 UTC, kelly1422 commented on Vegeting/Screens/GroupList/Component/ClubListCell.swift
> +class ClubListCell: UICollectionViewCell {
[d052317](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/56/commits/d0523179bf2e9d34035a2845bdb5e8c2516e75b4) 적용했습니다~

2022-10-31 18:20 UTC, kelly1422 commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +            collectionView.reloadData()
오 그렇군요!! 배워갑니다~
반영완료 [8bacd29](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/56/commits/8bacd2918fb68d4df37b2b90b0f31bf9209a658b)

2022-11-01 12:35 UTC, wonhui-kim requested changes

2022-11-01 12:35 UTC, wonhui-kim commented on Vegeting/Global/Supports/SceneDelegate.swift
> +             window.rootViewController = GroupListViewController()
p2;

rootView 원상복구 부탁드립니다!

2022-11-01 12:35 UTC, wonhui-kim commented on Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
> +    }()
p1;

외부에서 접근하지 않는 부분은 private으로 변경 부탁드립니다~
```suggestion
     private lazy var coverImage: UIImageView = {
        let imageView = UIImageView()
        imageView.image = UIImage(systemName: "star")
        return imageView
    }()
    
     private lazy var titleLabel: UILabel = {
        let label = UILabel()
        label.numberOfLines = 2
        label.tintColor = .black
        return label
    }()
```

2022-11-01 12:35 UTC, wonhui-kim commented on Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
> +        }
p3;

extension의 addSubviews를 이용하면 더 간단하게 표현할 수 있을 것 같아요!

2022-11-01 12:35 UTC, wonhui-kim commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +class GroupListViewController: ViewController {
p1;

UIViewController로 수정 부탁드립니다!
현재 코드는 기존 파일인 ViewController를 상속받고 있네요~

2022-11-01 12:35 UTC, wonhui-kim commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +        }
p3;

해당 부분도 extension의 addSubViews를 사용하면 간단하고 통일성 있는 코드가 될 것 같습니다 🙂

2022-11-01 12:35 UTC, wonhui-kim commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +    }
p2;

저희 코딩컨벤션에 따라 매개변수가 3개 이상인 경우 각 파라미터를 새로운 라인으로 만들어주면 더 깔끔한 코드가 될 것 같습니다!
```suggestion
    func collectionView(_ collectionView: UICollectionView,
     layout collectionViewLayout: UICollectionViewLayout, 
     sizeForItemAt indexPath: IndexPath) -> CGSize {
        return CGSize(width: (collectionView.frame.width - 20) / 2, height: 210)
    }
```

2022-11-01 12:35 UTC, wonhui-kim commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +        ]
p2;

해당 부분을 viewDidLoad() 에 넣으신 이유가 있을까요?
꼭 필요한 경우라면 따로 dummy data용 함수를 빼서 넣어주는 게 깔끔할 것 같습니다!

2022-11-01 17:34 UTC, kelly1422 commented on Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
> +        }
해당 함수가 UIView를 익스텐션 한건데, 콜렉션뷰셀이 UIView가 아니라 사용이 불가능 하더라구요!

참고 : 공식문서 https://developer.apple.com/documentation/uikit/uicollectionviewcell
@MainActor class UICollectionViewCell : UICollectionReusableView

2022-11-01 17:51 UTC, kelly1422 commented on Vegeting/Global/Supports/SceneDelegate.swift
> +             window.rootViewController = GroupListViewController()
[c0596ed](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/56/commits/c0596ed5b6a303416bc8deb6adab27c58a1683b4)
반영완료!

2022-11-01 17:52 UTC, kelly1422 commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +class GroupListViewController: ViewController {
[9e08584](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/56/commits/9e08584733ef900c688e62ef18df988d6d6bf2b7)
와우 에리하시군요!! 반영완료

2022-11-01 17:53 UTC, kelly1422 commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +        }
[6df1bac](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/56/commits/6df1bac731789bed74fa8f373084c3a390b06462)
반영완료!

2022-11-01 17:53 UTC, kelly1422 commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +    }
[dc9bdfe](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/56/commits/dc9bdfef53dbf211f48a29d38415ba0baa1a1a52)
반영완료!

2022-11-01 17:53 UTC, kelly1422 commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +        ]
[851e955](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/56/commits/851e95568002e40d183ec3a54a9e986dd370378c)
반영완료!

2022-11-01 23:12 UTC, wonhui-kim approved these changes
수고하셨습니다 🙂

2022-11-01 23:46 UTC, yudonlee commented on Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
> +        }
collectionViewCell은 내부에 contentView위에 Object들이 올라가며, contentView는 UIView를 상속하는 변수입니다.
따라서 기존에 구현한 addSubviews를 사용할 수 있게 됩니다.
```suggestion
        addSubviews(coverImage, titleLabel, placeLabelWithImage, countLabelWithImage)
```
### 참고
https://developer.apple.com/documentation/uikit/uicollectionviewcell/1620133-contentview

2022-11-02 01:20 UTC, kelly1422 commented on Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
> +    }()
[0be1931](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/56/commits/0be193198bd8ec1b964a64f9ebaf5f40e53ee52f)
반영완료!

2022-11-02 01:20 UTC, kelly1422 commented on Vegeting/Global/UIComponent/LabelWithImage.swift
> +    }
[0be1931](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/56/commits/0be193198bd8ec1b964a64f9ebaf5f40e53ee52f)
반영완료!

2022-11-02 01:21 UTC, ccdkk approved these changes
고생하셨씁니다~!

2022-11-02 01:22 UTC, kelly1422 commented on Vegeting/Global/Supports/SceneDelegate.swift
> +             window.rootViewController = GroupListViewController()
[c0596ed](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/56/commits/c0596ed5b6a303416bc8deb6adab27c58a1683b4)
반영완료!
근데 이거 닐이 리뷰 달아주기 전에 반영한건데 원래 리뷰할때는 
처음 PR 날린 이후에 커밋한 부분은 반영이 안되나요??

2022-11-02 02:35 UTC, yudonlee commented on Vegeting/Global/Supports/SceneDelegate.swift
> +             window.rootViewController = GroupListViewController()
반영되는데, 시점이 안맞았던게 아닐까 합니다~?

2022-11-02 02:40 UTC, kelly1422 commented on Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
> +    }()
[254147e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/56/commits/254147eba561caa6fd27c0b0e618015e72710418)
반영완료!

2022-11-02 06:24 UTC, yudonlee approved these changes

2022-11-03 14:25 UTC, merged