[FEAT] 지역검색시 검색 결과가 없는 경우 검색어 추천 기능 구현
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #93
Opened 2022-11-07 08:23 UTC by ccdkk

## 🌱 관련 이슈
- Close #58 

## 🌱 구현/변경 사항 및 이유
- 지역검색시 검색 결과가 없는 경우 빈화면이 뜨는데, 이게 어색하다고 생각하여 검색결과가 없는 경우 검색어 추천 리스트를 보여주기로 하였습니다.

## 🌱 PR Point
- 기존에 검색어가 없는 경우 emptyView를 띄워주려고 해당 코드를 작성해 놓았는데, 추후에 어떻게 변할지 몰라서 일단 관련 코드를 주석처리하여 남겨두었습니다.

## 🌱 참고 사항
- 자동 검색어 추천기능은 MapKit의 `MKLocalSearchCompleterDelegate`를 이용하여 구현하였습니다. 
```Swift
    private var autoSearchCompleter = MKLocalSearchCompleter()
    private var autoSearchResults = [MKLocalSearchCompletion]()

    autoSearchCompleter.queryFragment = "입력값"
```
`MKLocalSearchCompleter()`는 저희가 제공하는 query를 통해 추천 검색어를 리스트업을 수행합니다. 추천 검색어는 `MKLocalSearchCompletion` 타입으로 반환이 되고 저는 이 값들을 autoSearchResults에 할당하였습니다.
저장하는 코드는 `MKLocalSearchCompleterDelegate`에서 작성하였습니다.
```Swift
extension LocationSearchingViewController: MKLocalSearchCompleterDelegate {
    
    func completerDidUpdateResults(_ completer: MKLocalSearchCompleter) {
        let isResultNotEmpty = !completer.results.isEmpty
        if isResultNotEmpty {
            autoSearchResults = completer.results
        }
        
        DispatchQueue.main.async { [weak self] in
            self?.resultTableView.reloadData()
        }
    }
    
    func completer(_ completer: MKLocalSearchCompleter, didFailWithError error: Error) {
        print(error.localizedDescription)
    }
}

```
Completer가 Results를 출력하면 completerDidUpdateResults가 실행되어 결과물을 `autoSearchResults`에 할당하였습니다. completer가 값을 가져오는데 실패하면 error을 출력하도록 하였습니다.

![Simulator Screen Recording - iPhone 13 - 2022-11-07 at 17 15 36](https://user-images.githubusercontent.com/91456952/200259511-d623743b-d050-47ff-a6a3-5bdf682cc785.gif)

2022-11-07 15:48 UTC, yudonlee requested changes
해당 부분만 참고해주시면 더 좋을 것 같습니다~! 
수고하셨어요

2022-11-07 15:48 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +//    }
p1; 
주석인 지워주세요~

2022-11-07 15:48 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +//    }
P1; 
마찬가지입니다.

2022-11-07 15:48 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +                self.autoSearchCompleter.queryFragment = keyword
p2;
해당 항목들도 weak self로 안전하게 참조하는게 더 좋을 것 같습니다. 
사용자가 해당 statement가 이루어지는 도중에 ViewController를 나가게 됐을 때 memory leak이 발생할 수 있기 때문입니다.

2022-11-07 15:48 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +        }
```suggestion
        return totalCount == 0 ? autoSearchResults.count : totalCount
```
p2;
삼항연산자를 쓰게 되면 한줄로 간단하게 해결이 가능합니다.

2022-11-07 15:48 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
>          }
p3;
else문 안에 또다시 if-else를 두기보단 밖으로 빼는게 더 좋을 것 같습니다. 최대한 if-else의 depth를 가볍게 가져가는 게 좋은 구현이라고 생각합니다. 
```swift
if totalCount == 0 {
            cell.configure(with: autoSearchResults[indexPath.row].title)
        } else if indexPath.row < totalAddress {
            cell.configure(with: addressResultList[indexPath.row])
        } else {
            cell.configure(with: placeResultList[indexPath.row - totalAddress])
        }
```

2022-11-08 01:41 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +//    }
참고사항에 관련내용 남겨놓았습니다..!
> 기존에 검색어가 없는 경우 emptyView를 띄워주려고 해당 코드를 작성해 놓았는데, 추후에 어떻게 변할지 몰라서 일단 관련 코드를 주석처리하여 남겨두었습니다.

2022-11-08 01:41 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +//    }
참고사항에 관련내용 남겨놓았습니다..!
> 기존에 검색어가 없는 경우 emptyView를 띄워주려고 해당 코드를 작성해 놓았는데, 추후에 어떻게 변할지 몰라서 일단 관련 코드를 주석처리하여 남겨두었습니다.

2022-11-08 01:58 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +        }
오 훨씬 깔끔하네요 !!! [d81e9b3](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/93/commits/d81e9b367fc6aa72ca0e2d66cdc973ef871fb8ba)에서반영하였습니다. 삼항연산자 잘쓰면 좋군요!

2022-11-08 01:59 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +                self.autoSearchCompleter.queryFragment = keyword
[3e7d147](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/93/commits/3e7d14701466b77d81e075a6369511b161d63a1a)에서 반영하였습니다.
항상 메모리 관련해서 신경써줄 것들이 많네요! 메모리 관련해서 한 번 공부해봐야겠습니다. 
모든 후행클로져에 쓰는게 아니라 보통 escaping 클로져에서 self를 사용하는 경우에만 해주면 되나요?

2022-11-08 01:59 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
>          }
[f4d9ef3](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/93/commits/f4d9ef3cf08d553afb4d7a4116ad7872d0936010)에서 반영하였습니다.

2022-11-08 02:02 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +                self.autoSearchCompleter.queryFragment = keyword
https://ios-development.tistory.com/926를 참고해보시면 좋을 것 같습니다~

2022-11-08 02:26 UTC, kelly1422 approved these changes
이런것두 있었군요!! 수고하셨습니다~

2022-11-08 02:26 UTC, kelly1422 commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +            autoSearchResults = completer.results
q;
이 함수가 검색이 실행된 후에 실행되는 함수 인가요??
검색할때 입력한 검색어와 관련된 추천 검색어가 completer.results에 있는걸까요??

2022-11-08 02:30 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +            autoSearchResults = completer.results
넵 해당 함수는
```Swift
autoSearchCompleter.queryFragment = "입력값"
```
을 통해 Result가 update 되면 실행이되고 결과값이 `completer.results`에 있어서 이를 `autoSearchResults`에 할당해 주었습니다.

2022-11-08 06:25 UTC, ccdkk commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +                self.autoSearchCompleter.queryFragment = keyword
이렇게 뜨네요 ㅜㅜ
<img width="735" alt="스크린샷 2022-11-08 오후 3 25 03" src="https://user-images.githubusercontent.com/91456952/200490543-9b4229e4-be86-423b-aa2c-15b7c816845d.png">

2022-11-08 11:23 UTC, yudonlee commented on Vegeting/Screens/CreateGroup/ViewController/LocationSearchingViewController.swift
> +                self.autoSearchCompleter.queryFragment = keyword
다시 확인해주세요 @ccdkk 를이 붙어서 그런거 같아요

2022-11-10 13:11 UTC, merged