[FEAT]: 채팅방을 보여주는 뷰를 구현하였습니다.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #94
Opened 2022-11-07 08:49 UTC by ccdkk

## 🌱 관련 이슈
- Close #69 

## 🌱 구현/변경 사항 및 이유
- 채팅방을 tableView로 구현하였습니다.
- 채팅방 MockData와 MockModel을 만들었습니다.(데이터 연결 후 삭제예정)

## 🌱 PR Point
- 최근 메세지의 Date값을 convert해주는 함수를 다음과 같이 구현하였습니다.
```Swift
    private func convertDate(lastChatDate: Date) -> String {
        
        let now = Date()
        let nowTime = now.toString(format: "H m")
        let nowTimeList = nowTime.split(separator: " ")
        let nowTotalSeconds = (Double(nowTimeList[0]) ?? 0) * 3600 + (Double(nowTimeList[1]) ?? 0) * 60
        let timeIntervalFromNow = now.timeIntervalSince(lastChatDate)
        let isToday = timeIntervalFromNow <= nowTotalSeconds
        let isYesterday = nowTotalSeconds < timeIntervalFromNow && timeIntervalFromNow < nowTotalSeconds + 86400

        if isToday {
            return lastChatDate.toString(format: "a h:mm")
        }
        
        if isYesterday {
            return "어제"
        } else {
            return lastChatDate.toString(format: "M월 d일")
        }
        
    }
```
해당 메세지의 Date 값을 받아와서, 자정으로부터 얼만큼의 시간이 지났는지 `nowTotalSeconds`에서 count 합니다.
그 값을 기준으로 오늘, 어제, 그 이전을 분기처리하여 foramtter를 다르게 적용해주었습니다.
과정이 자연스러운지 확인 부탁드립니다.

## 🌱 참고 사항
![Simulator Screen Shot - iPhone 13 - 2022-11-07 at 17 37 54](https://user-images.githubusercontent.com/91456952/200265316-f6fe7fcd-f9a0-4e4b-9515-d870f44b1721.png)

2022-11-07 16:06 UTC, yudonlee requested changes
수고하셨어요!

2022-11-08 02:06 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +        let isYesterday = nowTotalSeconds < timeIntervalFromNow && timeIntervalFromNow < nowTotalSeconds + 86400
아니 이런게 있다구요,..? 왜 미리 말 안해주셨어요...

2022-11-08 02:09 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +        backgroundUnreadChatView.layer.cornerRadius = backgroundUnreadChatView.bounds.size.height / 2
이 부분을 짜면서 좀 의도대로 되지 않았던게, image의 height autoLayout으로 잡힌 이후에 cornerRadius를 그 height 값에 맞게 넣어 주는 플로우가 적절하다고 생각하여 추후에 넣어주는 방향으로 코딩을 하고 싶었는데 미리 imageView의 size를 지정해 주지 않으면 constraint를 준 이후에도 height 값이 0으로 뜨더라구요... 혹시 이와 관련해서 해결방법이 있을까요?

2022-11-08 02:22 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +        let isYesterday = nowTotalSeconds < timeIntervalFromNow && timeIntervalFromNow < nowTotalSeconds + 86400
[a25bdc8](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/94/commits/a25bdc8725bde388b6b95b20f2cbc170b906fea1)에서 반영하였습니다~

2022-11-08 11:26 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +        let isYesterday = nowTotalSeconds < timeIntervalFromNow && timeIntervalFromNow < nowTotalSeconds + 86400
좀 더 좋은 first party 기능을 서로 공유하는 것도 좋겠네요!

2022-11-08 11:29 UTC, yudonlee requested changes

2022-11-08 11:29 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
>              return lastChatDate.toString(format: "M월 d일")
이부분도 결국 3개의 flow중 하나로 가는 흐름이라 
if, else if, else로 구현하는게 더 좋은 것 같습니다~

2022-11-08 11:37 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
>              return lastChatDate.toString(format: "M월 d일")
또한 if문 두개라면, 두가지 모두 실행돼서 판단할 가능성이 있으나, if-else if- else로 이루어지는 구문을 통해 보다 효율적인 작동이 이루어질거라 생각합니다. 
Ex) Today일경우 두개의if 문이 실행돼서 판단 vs if - else if - else일경우 if문 한번 실행후 리턴

2022-11-08 12:41 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +        backgroundUnreadChatView.layer.cornerRadius = backgroundUnreadChatView.bounds.size.height / 2
음, 제가 생각하는 바는 autolayout으로 이미 constant를 70으로 지정했기 때문, cornerRadius도 view의 size.height 통해서 사이즈를 가져오지 않아도 될것 같습니다. 따라서 heightAnchor는 autolayout 하되, radius는 closure내부에서 우리가 constant값을 주는게 더 나을 것 같습니다. (만약 후에 사이즈가 바뀔 가능성이 있다면, height나 width를 제공하는 size literal을 생성하고 그걸 2로 나누는 방식이 좋을 것 같습니다.)

2022-11-08 12:47 UTC, yudonlee requested changes

2022-11-08 12:47 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +    }()
```suggestion
    private let roomImageView: UIImageView = {
        let imageView = UIImageView()
        imageView.layer.masksToBounds = true
        imageView.contentMode = .scaleAspectFill
        imageView.layer.cornerRadius = 35 // 혹은 우리가 지정한 sizeLiteral / 2 
        return imageView
    }()
```
## ScaleAspectFill
추가로 scaleAspectFill을 하지 않으셔서 말씀드립니다. 
### imageView의 default contentMode
만약 contentMode 설정을 하지 않는다면 default는 ScaleToFill이며 해당 조건은 기존에 사진의 비율을 무시한 채 크기에 맞게 넣게 됩니다.       
### ScaleAspectFill로 해야하는 이유 
현재 coverImage 예시 사진은 비율이 1:1비율이기 때문에 사진이 깨져보이지 않았지만 가로로 긴사진이나, 세로로 긴 사진의 경우 비율이 이상하게 보일 수 있습니다.     
그리하여 scaleAspectFill로 비율을 유지하되, maskToBounds로 70x70사이즈에 맞게 자르는게 제일 좋을 것 같습니다.    
현재 카카오가 프로필 사진에 쓰고 있는 방식과도  일치합니다~ scaleAspectFit으로 하게되면 비율을 유지한채 작은사이즈에 맞추기 때문에 공백이 생길 수 있습니다.    
## 참고
[참고링크](http://monibu1548.github.io/2018/05/21/scalemode/) 입니다~

2022-11-08 12:47 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +    }()
해당 부분도 이전 리뷰와 마찬가지 일 것 같습니다~

2022-11-09 01:54 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
>              return lastChatDate.toString(format: "M월 d일")
return 이 있어서 하나의 if문만 실행되는 것은 동일하지 않나요? 가독성적인 측면은 동의합니다

2022-11-09 01:57 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +    }()
이 부분은 image가 들어가지 않고 backgroundColor만 들어가기 때문에 수정하지 않아도 될 것 같아요!

2022-11-09 02:00 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +        backgroundUnreadChatView.layer.cornerRadius = backgroundUnreadChatView.bounds.size.height / 2
좋아요! size를 지정하는 메소드도 영향이 없는 것 같아 클로져에서 제거했습니다.
[2d5043e](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/94/commits/2d5043ef3b6ca8b3e3976ab14df2694c511f0420), [fadf26d](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/94/commits/fadf26de27288a0b0bceb15c4a6e738520607c2b)에서 반영하였습니다.

2022-11-09 02:01 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +    }()
오 놓치고 있던 부분인데 참고링크보고 완벽히 이해했습니다~!
[45cf834](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/94/commits/45cf8348074534373ac670db136b005b7cf20c96)에서 반영 완료!

2022-11-09 02:03 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
>              return lastChatDate.toString(format: "M월 d일")
[43c6653](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/94/commits/43c6653a410e3b1607dcf4d82c54382c48b6fa64) 여기에서 반영하였습니다!

2022-11-10 12:35 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +        backgroundUnreadChatView.layer.cornerRadius = backgroundUnreadChatView.bounds.size.height / 2
감사합니다~~

2022-11-10 12:41 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +    }()
데이크 제가 원하는대로 반영하셨는데 답글 안다신 이유가 있을까요~?🥲

2022-11-10 12:42 UTC, yudonlee approved these changes
고생하셨어요😁

2022-11-10 13:11 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
> +    }()
이 부분에 scaleAspectFill 적용하는거 말씀이신가요? 적용 안했어요..!

2022-11-11 00:21 UTC, merged