[FEAT]: 채팅방에서 보여줄 profile halfModal을 구현하였습니다.
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #95
Opened 2022-11-07 10:32 UTC by ccdkk

## 🌱 관련 이슈
- Close #76 

## 🌱 구현/변경 사항 및 이유
- profile HalfModal을 구현하였습니다.
- 해당 뷰가 뜨는 것을 보이기 위해 TestViewController를 추가하였습니다. 해당 뷰컨은 채팅View와 연결시키면 삭제하겠습니다.

## 🌱 PR Point
- 뭔가 이 뷰를 구현하면서 같은 디자인을 가지는 Label들을 굉장히 많이 만들게 되었는데, 코드들이 반복되는 것을 보면서 뭔가 좀 답답했던 것 같아요. 이런게 디자인시스템이 필요한 이유인 것 같기도 하고요! 그냥 그 때 느꼈던 감정을 주저리주저리 해봤습니다.

## 🌱 참고 사항
![Simulator Screen Recording - iPhone 13 - 2022-11-07 at 19 29 02](https://user-images.githubusercontent.com/91456952/200288210-134fb2c7-714d-4e62-b862-de4b99f6c891.gif)

2022-11-11 03:27 UTC, yudonlee requested changes
데이크의 코드 잘봤습니ㅏ. 전체적으로 깔끔하게 읽히는 거 같습니다.
더불어서 iPHONE SE3에서 modal이 잘못된 거 같으니 수정 바랍니다~~
![image](https://user-images.githubusercontent.com/39371835/201256557-5ec4d333-81c5-4a8b-8d4e-0341cd36067c.png)

2022-11-11 03:27 UTC, yudonlee commented on Vegeting/Global/UIComponent/ProfileVIew.swift
> +        imageView.layer.bounds.size = .init(width: 103, height: 103)
p2;
저번 pr에도 말씀드린 init부분입니다! autolayout으로 크기지정을 하기 때문에, 별도의 크기 지정이 필요 없으며 corner radius또한 저희가 임의로 하기 때문에 클로저 내부에서 하는 편이 더 가독성이 좋을 것 같아요!!

2022-11-11 03:27 UTC, yudonlee commented on Vegeting/Global/UIComponent/ProfileVIew.swift
> +
p1; Camel Case가 안지켜진 거 발견했어요!! 수정부탁드려요 ☺️

2022-11-11 03:27 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/Cell/InterestCollectionViewCell.swift
> +    }
p2;
이것또한 클로저 내부에서 하면 더 좋을 거 같아요!

2022-11-11 03:27 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/ViewController/TestViewController.swift
> +        viewController.configure(with: ModalModel(nickname: "내가 짱이얌", vegetarianStep: "플렉시테리언", ageGroup: "20대", location: "포항시 남구", gender: "여성", introduction: "사람을 좋아하고, 자연을 사랑하는 플렉시테리언입니다. 이곳에서 소중
p3;
가독성을 위해 modal configure를 위한 별도의 Structure하나를 만드시는 건 어떤가요?

2022-11-11 03:27 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/ViewController/TestViewController.swift
> +        viewController.configure(with: ModalModel(nickname: "내가 짱이얌", vegetarianStep: "플렉시테리언", ageGroup: "20대", location: "포항시 남구", gender: "여성", introduction: "사람을 좋아하고, 자연을 사랑하는 플렉시테리언입니다. 이곳에서 소중
p2;
TestViewController는 해당 모달 코드를 위해 만들어지는 거 같은데, 설명서 같은 느낌이라 없어도 될 듯 합니다!!

2022-11-11 14:59 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/ChatRoomTableViewCell.swift
>          }
develop merge하여 반영하였습니다!

2022-11-11 15:53 UTC, ccdkk commented on Vegeting/Global/UIComponent/ProfileVIew.swift
> +
[38c6577](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/95/commits/38c65775365b6589ca58c410ecc0335b3043a039)에서 반영하였습니다!

2022-11-11 16:00 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/ViewController/TestViewController.swift
> +        viewController.configure(with: ModalModel(nickname: "내가 짱이얌", vegetarianStep: "플렉시테리언", ageGroup: "20대", location: "포항시 남구", gender: "여성", introduction: "사람을 좋아하고, 자연을 사랑하는 플렉시테리언입니다. 이곳에서 소중
firebase서버와 연결이 되고 나면 VFUser로 configure를 해준다고 생각을 했습니다.
그러고보니 VFUser에 채식단계, 사는곳, 성별, 나이대 정보, 한줄소개, 관심사가 들어가야할 것 같아요!

2022-11-11 16:01 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/ViewController/TestViewController.swift
> +        viewController.configure(with: ModalModel(nickname: "내가 짱이얌", vegetarianStep: "플렉시테리언", ageGroup: "20대", location: "포항시 남구", gender: "여성", introduction: "사람을 좋아하고, 자연을 사랑하는 플렉시테리언입니다. 이곳에서 소중
half modal을 이전뷰에서 설정해야 해서 임시로 만들어 놓았습니다. 추후에 채팅방 프로필과 연결하고 없애도 괜찮을까요? 해당 코드를 그때 바로 쓰려고 합니다.

2022-11-11 16:02 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/Cell/InterestCollectionViewCell.swift
> +    }
[c3609bb](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/95/commits/c3609bb11cada86818faa31615b3a8eec866e105)에서 반영하였습니다!

2022-11-11 16:03 UTC, ccdkk commented on Vegeting/Global/UIComponent/ProfileVIew.swift
> +        imageView.layer.bounds.size = .init(width: 103, height: 103)
[c3609bb](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/95/commits/c3609bb11cada86818faa31615b3a8eec866e105)에서 반영하였습니다!

2022-11-12 13:33 UTC, yudonlee commented on Vegeting/Global/UIComponent/ProfileVIew.swift
>          imageView.layer.bounds.size = .init(width: 103, height: 103)
p3; 
이 부분의 삭제가 필요해보입니다! image 크기는 이미 저희가 103으로 알고 있는 상황이고, 그에따른 corner radius도 이미 알고 있는 상황입니다. 따라서 해당 값을 init해주는게 불필요하다고 판단됩니다!.

2022-11-12 13:33 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/ViewController/TestViewController.swift
> +        viewController.configure(with: ModalModel(nickname: "내가 짱이얌", vegetarianStep: "플렉시테리언", ageGroup: "20대", location: "포항시 남구", gender: "여성", introduction: "사람을 좋아하고, 자연을 사랑하는 플렉시테리언입니다. 이곳에서 소중
아! 제가 하고 싶었던건 
```swift
let modalModel = ModalModel(..) 
vc.configure(with: modalModel)
```
와 같이 선언된 모델을 대입하는 형식입니다. 한번만 쓸거라서 굳이 선언할 필요가 없다고 생각하실수도 있지만, parameter에 바로 생성후 넣는 것보다 가독성이나 후에 유지보수에 도움이 될 거 같습니다.

2022-11-12 13:34 UTC, yudonlee commented on Vegeting/Screens/ChatRoom/ViewController/TestViewController.swift
> +        viewController.configure(with: ModalModel(nickname: "내가 짱이얌", vegetarianStep: "플렉시테리언", ageGroup: "20대", location: "포항시 남구", gender: "여성", introduction: "사람을 좋아하고, 자연을 사랑하는 플렉시테리언입니다. 이곳에서 소중
네 좋습니다~~~

2022-11-12 14:14 UTC, ccdkk commented on Vegeting/Screens/ChatRoom/ViewController/TestViewController.swift
> +        viewController.configure(with: ModalModel(nickname: "내가 짱이얌", vegetarianStep: "플렉시테리언", ageGroup: "20대", location: "포항시 남구", gender: "여성", introduction: "사람을 좋아하고, 자연을 사랑하는 플렉시테리언입니다. 이곳에서 소중
아하! 동의합니다! [e5cc390](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/95/commits/e5cc390aed069d0fe6f627a139e67a753726ebf3)에서 반영하였습니다. 훨씬 보기 깔끔하네요!

2022-11-12 14:17 UTC, ccdkk commented on Vegeting/Global/UIComponent/ProfileVIew.swift
>          imageView.layer.bounds.size = .init(width: 103, height: 103)
[657dbeb](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/95/commits/657dbeba48dc2b8b83c13d61f76cafec514bd8af)에서 반영하였습니다!!

2022-11-13 05:53 UTC, ccdkk commented
@yudonlee 일단 디자인 요구사항처럼 halfModal의 가운데에 배치하는 방법은 찾지 못했습니다 ㅜㅜ.. 
그래서 hifi에서는 profile뷰의 height가 줄어들기 때문에 hifi를 적용함으로써 se모델에서 ui가 잘리던 현상을 수정하였습니다.

<img src="https://user-images.githubusercontent.com/91456952/201507932-ede829d9-0986-48ca-879c-23cef8f7d7ff.png" width="390" height="844">

2022-11-13 07:48 UTC, ccdkk commented
@yudonlee  알려주신 방법으로 성공했습니다. 1.0으로 하니 되네요. 근데 어떻게 작동하는 로직인지는 아직 이해를 못해서..
나중에 공부해보고 공유해보겠습니다.
위에는 se3 , 아래는 iPhon13 입니다.

<img width="313" alt="스크린샷 2022-11-13 오후 4 44 01" src="https://user-images.githubusercontent.com/91456952/201511532-4410a3ba-f60f-413e-bb4e-0bf420e01765.png">
<img width="273" alt="스크린샷 2022-11-13 오후 4 43 21" src="https://user-images.githubusercontent.com/91456952/201511534-00816103-6f59-42cd-a707-043a821b2891.png">

2022-11-14 00:44 UTC, yudonlee approved these changes
고생하셨어요~~

2022-11-14 00:44 UTC, merged