[FEAT]: 모임글 리스트 뷰 커스텀 네비바, 세그먼트컨트롤 구현
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #97
Opened 2022-11-08 02:37 UTC by kelly1422

## 🌱 관련 이슈
#62 

## 🌱 구현/변경 사항 및 이유
 커스텀 네비바 추가
 커스텀 세그먼트

## 🌱 PR Point

## 🌱 참고 사항
<img src="https://user-images.githubusercontent.com/80809782/200461171-d23457f4-eaaa-4288-a613-c22f4632fd14.png" width="30%">

2022-11-09 01:34 UTC, yudonlee commented on Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
> +        placeLabel.setCoverImage(image: UIImage(systemName: "mappin",
SF symbol에서 받아온 사진을 넣는 과정에서 optional이 필요한 순간이 있을까요~?

2022-11-09 01:34 UTC, yudonlee commented on Vegeting/Screens/GroupList/ViewController/GroupListViewController.swift
> +    }
p4;
저희 별도의 convention을 설정하지 않았는데, 
```swift
 didAddClubButtonTapped()
addClubButtonTapped()
```
둘중 하나로 convention을 맞출 필요가 있을 것 같네요.

2022-11-09 01:34 UTC, yudonlee commented on Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
> +    @objc private func didTapTab(_ sender: UIButton) {
해당 부분도 위와 마찬가지로 convention 확립이 필요할 것 같습니다.

2022-11-09 01:34 UTC, yudonlee commented on Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
> +
q; 
해당 부분을 보면, stackView의 layout이 확립되기전에 해당 leading anchor들을 넘겨주는 방식인 것 같아요.
이것이 후에 UI를 조정하는등을 거쳐서 segment의 위치가 바뀐다면 다소 문제가 될 수 있는 가능성은 없을까요? 
지금은 현재 StackView의 위치가 자동적으로 가장 상단에 위치하게 디자인 되었기에 default 위치와 문제가 없어 보여서요! 
제가 생각한 가능성은 segmentStackView의 위치와 indicatorView가 맞지 않을 수 있다는 생각이 들어요.

2022-11-09 17:04 UTC, kelly1422 commented on Vegeting/Global/UIComponent/LabelWithImageStackView.swift
> +        imageView.tintColor = UIColor(hex: "333333", alpha: 0.7)
동의합니다!

2022-11-09 17:07 UTC, kelly1422 commented on Vegeting/Global/UIComponent/LabelWithImageStackView.swift
> +        label.textColor = UIColor(hex: "333333", alpha: 0.7)
넵 맞습니다!

2022-11-09 17:09 UTC, kelly1422 commented on Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
> +        placeLabel.setCoverImage(image: UIImage(systemName: "mappin",
저도 optional이 필요하지 않을거라 생각했는데 에러가 발생해서 일단 집어 넣은 코드인데 혹시 다른 방법이 있을까요?
<img width="1218" alt="스크린샷 2022-11-10 오전 2 08 55" src="https://user-images.githubusercontent.com/80809782/200895405-7327870b-90f2-4d3e-815d-69eb037c6e1e.png">

2022-11-09 17:45 UTC, kelly1422 commented on Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
> +
흠 일단 제가 이해한 바로는 stackView의 layout이 확립되기전에 indicatorView의 leadingAnchor, trailingAnchor 을 지정해주고 있어서 나중에 stackView의 위치가 바뀌게 되면 문제가 생길 수 있다로 들리는데 맞을까요? 
이 부분은 만나서 이야기해보는게 좋을것 같아요 글로만 보니 닐의 생각을 완벽히 이해하기 좀 어렵습니돠

2022-11-09 17:47 UTC, kelly1422 commented on Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
> +    @objc private func didTapTab(_ sender: UIButton) {
[7282cb2](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/97/commits/7282cb25a2a3ccea53dd23e691ad40bc368d2f67)
적용 완료!

2022-11-11 05:17 UTC, yudonlee commented on Vegeting/Global/UIComponent/LabelWithImageStackView.swift
> +        imageView.tintColor = UIColor(hex: "333333", alpha: 0.7)
따로 관리되는 Literal을 해당 file에서라도 하는건 어떨까요?

2022-11-11 06:28 UTC, kelly1422 commented on Vegeting/Global/UIComponent/LabelWithImageStackView.swift
> +        label.textColor = UIColor(hex: "333333", alpha: 0.7)
[c2d8223](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/97/commits/c2d8223b20bb662593b2d719ab9f6f69f499eb06)
적용완료!

2022-11-11 06:28 UTC, kelly1422 commented on Vegeting/Global/UIComponent/LabelWithImageStackView.swift
> +        imageView.tintColor = UIColor(hex: "333333", alpha: 0.7)
[c2d8223](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/97/commits/c2d8223b20bb662593b2d719ab9f6f69f499eb06)
적용완료!

2022-11-11 10:09 UTC, yudonlee commented on Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
> +
제가 봐도 이해하기 힘들게 쓴거 같네요! 단계를 통해 설명드릴게요.
1. leadingAnchors들이 segmentStackView의 autolayout이 확정되기 전에 값을 가져왔다
2. trailing또한 segmentStackView의 autolayout이 확정되기 전에 값을 가져왔다
3. 그리고 마지막으로 segmentStackView의 autolayout이 확정됐다. 
4. 확정되기 전 segmentStackView의 autolayout을 가져오는 건 위험할 거 같은데?!
1-4번이 제 생각의 흐름이였습니다~~

2022-11-11 10:33 UTC, kelly1422 commented on Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
> +
아하 넵
저도 닐의 리뷰를 보고 그 부분이 걸려서 문제가 발생하도록 segmentStackView의 autolayout을 좀 수정해서 실행해봤는데 신기하게 segmentStackView의 autolayout에 맞게 잘 설정이 되더라구요! 이유는 잘 모르겠지만 혹시 모르니 순서를 바꿨습니다!
[618a903](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/97/commits/618a9033a23e32054e4159dd6aac61ad2d182e75)

2022-11-11 10:58 UTC, yudonlee commented on Vegeting/Global/UIComponent/LabelWithImageStackView.swift
> +        imageView.tintColor = UIColor(hex: "333333", alpha: 0.7)
제로!!! label..gay로 오타내신거 같아요. 
p3;
추가적으로 UIColor에 extension으로 하기 보단 enum이나 별도의 Literal을 만들어서 하는건 어떤가요?
저희가 extension이 너무 많아서 extension에 추가되는 걸 지양하고 싶은 마음이 있는 것 같습니다~

2022-11-11 11:07 UTC, yudonlee commented on Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
> +        placeLabel.setCoverImage(image: UIImage(systemName: "mappin",
제가 생각하기엔, UImageView의 image로 optional 타입이기 때문에, setCoverImage의 parameter type또한 optional로 하는 방법은 어떨까요? imageView내부 variable인 image의 전제가 잘못 불러져 올수 있다는 전제로 optional type이기 때문입니다! 
https://developer.apple.com/documentation/uikit/uiimageview

2022-11-11 11:07 UTC, yudonlee requested changes

2022-11-11 11:08 UTC, yudonlee commented on Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
> +
제가 말을 두서없이 했는데 감사합니다~~ 잘 설정되었던 이유도 고민해보면 좋겠네요.

2022-11-12 00:16 UTC, kelly1422 commented on Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
> +            button.addTarget(self, action: #selector(tabButtontapped(_:)), for: .touchUpInside)
[1091351](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/97/commits/1091351d714d9018ceb8f2b0f7bff388729b43f9)
예리하십니다👍

2022-11-12 00:25 UTC, kelly1422 commented on Vegeting/Global/UIComponent/LabelWithImageStackView.swift
> +        imageView.tintColor = UIColor(hex: "333333", alpha: 0.7)
어이쿠 일단 급하게 오타부터 수정했습니다 [1091351](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/97/commits/1091351d714d9018ceb8f2b0f7bff388729b43f9)

컬러들을 정의할 땐 extension에 추가하는 방법이 주로 쓰이는 것 같은데, 파일이 많아지는 것 제외하고 혹시 지양하시는 다른 이유가 있으실까요?
UIColor extension파일은 이미 존재하기도 하고, 
이런 코드 말고 UIColor extension파일에 추가될만한 코드가 많이 없을것 같아서요.

데이크도 이미 UIColor extension파일에 컬러들을 추가하셨더라구요 😅 후딱 정하면 좋을것 같습니돠

2022-11-12 12:27 UTC, kelly1422 commented on Vegeting/Screens/GroupList/Component/ClubListCollectionViewCell.swift
> +        placeLabel.setCoverImage(image: UIImage(systemName: "mappin",
좋은 생각이군요!! 적용했습니다 [176322c](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/97/commits/176322c5b0e0fac6075fb5ed7375a3bb86eb4e7b)

2022-11-12 12:39 UTC, yudonlee commented on Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
> +            button.addTarget(self, action: #selector(tabButtontapped(_:)), for: .touchUpInside)
Tapped도 camelcase 적용이 필요해보여요!😀

2022-11-13 03:41 UTC, yudonlee commented on Vegeting/Global/UIComponent/LabelWithImageStackView.swift
> +        imageView.tintColor = UIColor(hex: "333333", alpha: 0.7)
Extension이 너무 많다보니, 서로가 무엇을 활용할 수 있는지 잘 모르는 것 같았어요. 그래서 관리되지 않을 것 같아 추후에 Extension을 제거하는 쪽으로 생각해서 지양하고자 했습니다. 
일단 Hi-fi가 확립되는 대로 따로 Literal를 만들어 관리하는 걸로 하겠습니다.

2022-11-13 03:42 UTC, yudonlee commented on Vegeting/Screens/GroupList/Component/SegmentedControlCustomView.swift
> +            button.addTarget(self, action: #selector(tabButtontapped(_:)), for: .touchUpInside)
잘못봤어요 🥹

2022-11-13 03:42 UTC, yudonlee approved these changes

2022-11-13 06:18 UTC, merged