Feature/72 profile nickname
DeveloperAcademy-POSTECH/MacC-Team-Vegeting pull request #99
Opened 2022-11-08 10:16 UTC by wonhui-kim

## 🌱 관련 이슈
- #72 

## 🌱 구현/변경 사항 및 이유
- 프로그레스바는 버튼 선택 구현이 필요 없을 듯 하여 이미지로 구현하였습니다.
- 닉네임 제한은 2-10글자로 설정 후, 변경을 감지하여 10글자 이상인 경우 더 이상 입력되지 않도록 구현했습니다.
- 사진은 옵셔널, 닉네임은 필수값으로 닉네임을 정상적으로 작성 시 다음 버튼이 활성화되도록 구현했습니다.

## 🌱 PR Point

## 🌱 참고 사항

!<img src="https://user-images.githubusercontent.com/96123303/200537434-4a1fd37f-fa13-40e9-8e19-1c863740d015.mp4" width=200/>

2022-11-09 23:26 UTC, yudonlee requested changes

2022-11-09 23:26 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +                }
p2;
weak self를 지켜주세요, 추가로 image를 UIImage로 typecasting 하는 이유가 있을까요?

2022-11-10 14:51 UTC, ccdkk reviewed
progress bar들의 이미지가 jpg로 들어와서 배경색이 흰색으로 남아있는 것 같습니다.
현재는 배경이 흰색이고 light 모드만 지원하기 때문에 괜찮지만 추후에 변동 사항이 생기면 영향이 있을 것 같아서 svg 파일이나 png 파일로 넣어보는 것은 어떨까요? 
제가 테스트 해봤는데 png 파일은 그래픽이 좀 깨져서 svg로 넣어도 좋을 것 같아요!

2022-11-10 14:51 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +        button.addTarget(self, action: #selector(presentPicker), for: .touchUpInside)
p2;
button action 컨벤션에 맞게 cameraButtonTapped로 수정부탁드려요~

2022-11-10 14:51 UTC, ccdkk commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +                                               object: nicknameTextField)
q5;
오 NotificationCenter를 이용해서 textField의 changed 함수를 구현하셨군요! 
제가 알기론 notificationCenter를 이용한 후 observer를 remove해주지 않으면 메모리 누수가 발생하는 것으로 알고 있어요!
그래서 어느 lifeCycle에서는 `NotificationCenter.default.removeObserver`를 통해서 remove를 해줘야 하는데, 제가 생각했을 때 다음 view로 넘어가도 닉네임을 다시 수정하러 오는 경우가 있을 것이기 때문에 해당 viewController가 navigationConrtoller에서 pop되는 순간인 `deinit` 시점에서 remove해주면 좋을 것 같습니다!
관련 참고자료를 첨부합니다!
deinit: [https://baked-corn.tistory.com/132](https://baked-corn.tistory.com/132)

라고 작성하고 있었는데 공식문서를 참고하니까
<img width="729" alt="스크린샷 2022-11-10 오후 11 45 35" src="https://user-images.githubusercontent.com/91456952/201122015-2fd9b03f-03f6-4b5b-b17e-c548ad8f06e4.png">

이런 경우에는 removeObserver를 알아서 해준다고 하네요?! 처음 알았습니다. 
위의 경우가 저 경우에 해당되는 것 같아서 remove 해줄필요가 없겠네요..🤩

별개로 저도 방금 textField changed관련 함수를 찾아봤었는데 
```Swift
textField.addTarget(self, action: #selector(didTextFieldChanged), for: .editingChanged)
```
이런식으로 editingChange으로 구현하기도 하더라구요! 구현하신 내용과 비슷한 것 같아서 남깁니다!

2022-11-13 11:50 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +}
해당 메서드의 필요 목적은
maxLength 초과 시 false를 반환함으로써 textField에 입력하지 못하도록 막는 역할을 합니다.
range의 location은 텍스트의 변경이 일어난 위치를 반환, length는 변경이 일어난 크기(개수)를 반환합니다.

현재 글자수가 maxLength라도 중간의 값을 지우면 range.length는 증가하기 때문에 
range.length가 0이 아니면 텍스트 변경(지우기 가능)이 가능하도록 했습니다. 

즉, 해당 메서드는
텍스트필드에 입력된 글자수가 maxLength 이상이면서, 지우지 않은 상태이며(range.length가 0), 변경이 일어나는 위치가 maxLength 이하이면(range.location이 maxLength보다 작으면) textField에 변경이 일어나지 않도록 한다는 의미입니다.

[shouldChangeCharactersIn](https://loganberry.tistory.com/16)
[NSRange의 역할](https://zeddios.tistory.com/425)

2022-11-13 11:55 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +                }
itemProvider를 통해 전달되는 item이 NSItemProviderReading 타입이기 때문에 typecasting 해주었습니다!

<img src="https://user-images.githubusercontent.com/96123303/201520300-b1919719-1de7-452b-8e7a-5f98eb9ff67f.png" width=300>

2022-11-13 12:46 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +        imageView.backgroundColor = UIColor(hex: "#F2F2F2")
해당 부분은 추후에 하이파이가 나오면 전면 수정하도록 하겠습니다!
enum으로 지정 시 UIColor extension 파일을 건드리게 되어 공통되는 색깔을 설정한 후에 하면 좋겠습니다 🙂

2022-11-13 12:47 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +            if let text = nicknameTextField.text {
https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/99/files#diff-d95417c458a8528974d98adab570fc3e6ffedf546ea53c010fbdf052c46d30d8R177
수정하였습니다!
추가로, NotificationCenter 대신 textField의 addTarget 메서드를 사용하는 것으로 변경해줌에 따라 notification.object 구문도 삭제했습니다 🙂

2022-11-13 12:50 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +                } else if text.count < nicknameMinLength {
shouldChangeCharactersIn 메서드 해당 값을 출력해보면 변경 **이전**의 값이 출력됩니다.
예를 들어 텍스트 필드 한 칸 입력완료 시 text.count는 0이 됩니다!
따라서 초과가 아닌 이상 으로 해주었습니다.

참고 [블로그](https://zeddios.tistory.com/425)입니다!

2022-11-13 12:51 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +        guard let text = textField.text else { return false}
[반영](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/99/files#diff-d95417c458a8528974d98adab570fc3e6ffedf546ea53c010fbdf052c46d30d8R209)하였습니다~

2022-11-13 12:52 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +                }
✨✨✨weak self 습관화✨✨✨
[반영](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/99/files#diff-d95417c458a8528974d98adab570fc3e6ffedf546ea53c010fbdf052c46d30d8R228-R230)하였습니다 🌝

2022-11-13 12:53 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +        button.addTarget(self, action: #selector(presentPicker), for: .touchUpInside)
앗! [수정](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/99/files#diff-d95417c458a8528974d98adab570fc3e6ffedf546ea53c010fbdf052c46d30d8R46)하였습니다 😄

2022-11-13 12:56 UTC, wonhui-kim commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +                                               object: nicknameTextField)
notificationCenter observer 사용 시 remove를 해주지 않으면 메모리 누수!! 
몰랐어요~
다행히 자동 removeObserver가 되군요!! 
꼼꼼히 찾아보는 자세 멋집니다👍

+ textField의 addTarget도 같은 역할을 하는군요! 감사해요
메서드 호출부, 메서드 정의부 모두 간단해지는 장점에 [변경](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-Vegeting/pull/99/files#diff-d95417c458a8528974d98adab570fc3e6ffedf546ea53c010fbdf052c46d30d8R101)해보았습니다 😄

2022-11-14 00:47 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +            if let text = nicknameTextField.text {
고생하숐숩니당 😁

2022-11-14 00:48 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +                } else if text.count < nicknameMinLength {
아! 변경 이전에 호출되는 델리게이트 메서드 였군요~~ 감사합니다 👍

2022-11-14 00:50 UTC, yudonlee commented on Vegeting/Screens/RegisterUserProfile/UserProfileViewController.swift
> +}
아!!! 설명보고 이해가 됐습니다 감사합니다. maxlength 이상이고, range length가 0인 상황에서 수정이 안되는 거였군요

2022-11-14 00:51 UTC, yudonlee approved these changes
고생하셨어요!

2022-11-14 01:05 UTC, ccdkk approved these changes
고생하셨습니다 !!

2022-11-14 05:00 UTC, merged